server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # ── Backend proxy — Option 1: regex (URL უცვლელია, მხოლოდ nginx-ს ეხება) ──
    # VITE_API_URL = http://192.168.1.199:8083
    location ~ ^/(api|sign)/ {
        proxy_pass http://192.168.1.199:8083;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ── Backend proxy — Option 2: prefix (VITE_API_URL = .../backend) ──────────
    # VITE_API_URL = http://192.168.1.199:5175/backend
#     location /backend/ {
#         proxy_pass http://192.168.1.199:8083/;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#     }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # Security headers
#     add_header Content-Security-Policy "frame-ancestors https://chat.geostat.ge http://192.168.1.199:5175 http://localhost:5173 http://localhost:5174 http://192.168.1.199:5173 https://www.geostat.ge" always;
#     add_header X-Content-Type-Options "nosniff" always;
#     add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;
    gzip_min_length 1024;
}