server:
  port: 8081

security:
  type: api

spring:
  config:
    import: optional:classpath:application-local.yml
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
      file-size-threshold: 0B
      location: /app/uploads
  main:
    allow-bean-definition-overriding: true
  application:
    name: api
  datasource:
    primary:
      jdbc-url: ${DB_PRIMARY_URL}
      username: ${DB_PRIMARY_USER}
      password: ${DB_PRIMARY_PASS}
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    secondary:
      jdbc-url: ${DB_SECONDARY_URL}
      username: ${DB_SECONDARY_USER}
      password: ${DB_SECONDARY_PASS}
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        order_updates: true
        order_inserts: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR

storage:
  export-dir: api/storage/access_exports
