server:
  port: 8081

security:
  type: api

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
      file-size-threshold: 0B
      location: /tmp/uploads
  main:
    allow-bean-definition-overriding: true
  application:
    name: api
  datasource:
    # --- MS SQL Primary Connection ---
    primary:
      jdbc-url: jdbc:sqlserver://192.168.0.230;databaseName=geostat-system;useBulkCopyForBatchInsert=true;encrypt=true;trustServerCertificate=true;serverTimezone=Asia/Tbilisi;cachePrepStmts=true;reWriteBatchedInserts=true
      username: sa
      password: Ozzy112358
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # --- MS SQL Secondary Connection ---
    secondary:
      jdbc-url: jdbc:sqlserver://192.168.0.230;databaseName=auto;encrypt=true;useBulkCopyForBatchInsert=true;trustServerCertificate=true;serverTimezone=Asia/Tbilisi;cachePrepStmts=true;reWriteBatchedInserts=true
      username: sa
      password: Ozzy112358
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # --- Your New MySQL Connection ---
    tertiary:
      jdbc-url: jdbc:mysql://192.168.1.29:3306/soplis_meurneoba?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: fdi
      password: Asd123$%
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        format_sql: true
        # This dialect will be overridden by the specific configs, but it's good to have a default
        dialect: org.hibernate.dialect.SQLServerDialect
        order_updates: true
        order_inserts: true

jwt:
  secret: "5A7C8E1F2A3C5E7A8C1E2F3A5C7E8A1F2C3F5A7C8E1F2A3C5E7A8C1E2F3A5C7E"
  expiration: 86400000
  refresh-expiration: 86400000

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
storage:
  export-dir: api/storage/access_export