/* Run in geostat-data. Shared active data plane; no per-site business tables. */
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'ingest') EXEC(N'CREATE SCHEMA ingest');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'raw') EXEC(N'CREATE SCHEMA raw');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'entity') EXEC(N'CREATE SCHEMA entity');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'statistics') EXEC(N'CREATE SCHEMA [statistics]');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'geo') EXEC(N'CREATE SCHEMA geo');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'reference') EXEC(N'CREATE SCHEMA reference');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'publication') EXEC(N'CREATE SCHEMA publication');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'serving') EXEC(N'CREATE SCHEMA serving');

IF OBJECT_ID(N'ingest.batch',N'U') IS NULL CREATE TABLE ingest.batch (batch_id BIGINT IDENTITY PRIMARY KEY, contract_id BIGINT NOT NULL, product_id BIGINT NOT NULL, status VARCHAR(24) NOT NULL, checksum CHAR(64) NULL, requested_by_user_id BIGINT NULL, started_at DATETIME2 NULL, finished_at DATETIME2 NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID(N'ingest.artifact',N'U') IS NULL CREATE TABLE ingest.artifact (artifact_id BIGINT IDENTITY PRIMARY KEY, batch_id BIGINT NOT NULL, original_name NVARCHAR(512) NOT NULL, format VARCHAR(32) NOT NULL, object_uri NVARCHAR(2048) NOT NULL, checksum CHAR(64) NOT NULL, byte_size BIGINT NOT NULL, received_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT fk_artifact_batch FOREIGN KEY(batch_id) REFERENCES ingest.batch(batch_id));
IF OBJECT_ID(N'ingest.dataset_load',N'U') IS NULL CREATE TABLE ingest.dataset_load (dataset_load_id BIGINT IDENTITY PRIMARY KEY, batch_id BIGINT NOT NULL, dataset_version_id BIGINT NOT NULL, source_name NVARCHAR(255) NOT NULL, source_row_count BIGINT NULL, accepted_count BIGINT NULL, rejected_count BIGINT NULL, status VARCHAR(24) NOT NULL, CONSTRAINT fk_dataset_load_batch FOREIGN KEY(batch_id) REFERENCES ingest.batch(batch_id));
IF OBJECT_ID(N'ingest.staged_row',N'U') IS NULL CREATE TABLE ingest.staged_row (staged_row_id BIGINT IDENTITY PRIMARY KEY, dataset_load_id BIGINT NOT NULL, source_row_number BIGINT NOT NULL, source_key NVARCHAR(512) NULL, raw_payload_json NVARCHAR(MAX) NOT NULL, payload_hash CHAR(64) NOT NULL, validation_status VARCHAR(24) NOT NULL DEFAULT 'PENDING', error_json NVARCHAR(MAX) NULL, CONSTRAINT fk_staged_row_load FOREIGN KEY(dataset_load_id) REFERENCES ingest.dataset_load(dataset_load_id));
IF OBJECT_ID(N'ingest.validation_issue',N'U') IS NULL CREATE TABLE ingest.validation_issue (issue_id BIGINT IDENTITY PRIMARY KEY, staged_row_id BIGINT NOT NULL, rule_code NVARCHAR(128) NOT NULL, severity VARCHAR(16) NOT NULL, message NVARCHAR(2000) NOT NULL, details_json NVARCHAR(MAX) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT fk_validation_issue_row FOREIGN KEY(staged_row_id) REFERENCES ingest.staged_row(staged_row_id));
IF OBJECT_ID(N'publication.snapshot',N'U') IS NULL CREATE TABLE publication.snapshot (snapshot_id BIGINT IDENTITY PRIMARY KEY, product_id BIGINT NOT NULL, release_id BIGINT NOT NULL, status VARCHAR(24) NOT NULL, published_at DATETIME2 NULL, previous_snapshot_id BIGINT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE name=N'uq_publication_snapshot_release') ALTER TABLE publication.snapshot ADD CONSTRAINT uq_publication_snapshot_release UNIQUE(release_id);
/* One immutable materialized version of a logical dataset, used by raw/entity/statistical/geo rows. */
IF OBJECT_ID(N'publication.dataset_snapshot',N'U') IS NULL CREATE TABLE publication.dataset_snapshot (dataset_snapshot_id BIGINT IDENTITY PRIMARY KEY, dataset_load_id BIGINT NOT NULL, dataset_version_id BIGINT NOT NULL, status VARCHAR(24) NOT NULL DEFAULT 'PREPARED', row_count BIGINT NOT NULL DEFAULT 0, checksum CHAR(64) NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT uq_dataset_snapshot_load UNIQUE(dataset_load_id), CONSTRAINT fk_dataset_snapshot_load FOREIGN KEY(dataset_load_id) REFERENCES ingest.dataset_load(dataset_load_id));
IF OBJECT_ID(N'publication.snapshot_member',N'U') IS NULL CREATE TABLE publication.snapshot_member (snapshot_id BIGINT NOT NULL, dataset_version_id BIGINT NOT NULL, dataset_snapshot_id BIGINT NOT NULL, row_count BIGINT NOT NULL, checksum CHAR(64) NULL, CONSTRAINT pk_snapshot_member PRIMARY KEY(snapshot_id,dataset_version_id), CONSTRAINT fk_snapshot_member_snapshot FOREIGN KEY(snapshot_id) REFERENCES publication.snapshot(snapshot_id));
IF OBJECT_ID(N'raw.source_record',N'U') IS NULL CREATE TABLE raw.source_record (source_record_id BIGINT IDENTITY PRIMARY KEY, dataset_snapshot_id BIGINT NOT NULL, artifact_id BIGINT NOT NULL, source_row_number BIGINT NOT NULL, source_key NVARCHAR(512) NULL, payload_json NVARCHAR(MAX) NOT NULL, payload_hash CHAR(64) NOT NULL, extracted_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), valid_from DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), valid_to DATETIME2 NULL, CONSTRAINT fk_raw_artifact FOREIGN KEY(artifact_id) REFERENCES ingest.artifact(artifact_id));
IF OBJECT_ID(N'entity.entity_record',N'U') IS NULL CREATE TABLE entity.entity_record (entity_id BIGINT IDENTITY PRIMARY KEY, dataset_snapshot_id BIGINT NOT NULL, external_key NVARCHAR(512) NULL, record_type VARCHAR(32) NOT NULL, title NVARCHAR(512) NULL, payload_json NVARCHAR(MAX) NOT NULL, payload_hash CHAR(64) NOT NULL, source_record_id BIGINT NOT NULL, valid_from DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), valid_to DATETIME2 NULL, is_current BIT NOT NULL DEFAULT 1, CONSTRAINT fk_entity_source FOREIGN KEY(source_record_id) REFERENCES raw.source_record(source_record_id));
IF OBJECT_ID(N'entity.entity_link',N'U') IS NULL CREATE TABLE entity.entity_link (link_id BIGINT IDENTITY PRIMARY KEY, from_entity_id BIGINT NOT NULL, relationship_type_id BIGINT NOT NULL, to_entity_id BIGINT NOT NULL, ordinal INT NULL, valid_from DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), valid_to DATETIME2 NULL, source_record_id BIGINT NULL, CONSTRAINT fk_entity_link_from FOREIGN KEY(from_entity_id) REFERENCES entity.entity_record(entity_id), CONSTRAINT fk_entity_link_to FOREIGN KEY(to_entity_id) REFERENCES entity.entity_record(entity_id));
IF OBJECT_ID(N'entity.entity_classification',N'U') IS NULL CREATE TABLE entity.entity_classification (entity_id BIGINT NOT NULL, attribute_id BIGINT NOT NULL, classification_item_id BIGINT NOT NULL, valid_from DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), valid_to DATETIME2 NULL, source_record_id BIGINT NULL, CONSTRAINT pk_entity_classification PRIMARY KEY(entity_id,attribute_id,classification_item_id,valid_from), CONSTRAINT fk_entity_classification_entity FOREIGN KEY(entity_id) REFERENCES entity.entity_record(entity_id));
IF OBJECT_ID(N'statistics.series',N'U') IS NULL CREATE TABLE [statistics].series (series_id BIGINT IDENTITY PRIMARY KEY, dataset_snapshot_id BIGINT NOT NULL, metric_id BIGINT NOT NULL, series_key_hash CHAR(64) NOT NULL, unit_code NVARCHAR(64) NULL, status VARCHAR(24) NOT NULL, source_record_id BIGINT NULL, CONSTRAINT uq_statistics_series UNIQUE(dataset_snapshot_id,metric_id,series_key_hash));
IF OBJECT_ID(N'statistics.observation',N'U') IS NULL CREATE TABLE [statistics].observation (observation_id BIGINT IDENTITY PRIMARY KEY, series_id BIGINT NOT NULL, period_start DATE NULL, period_end DATE NULL, observation_status VARCHAR(24) NOT NULL DEFAULT 'VALID', numeric_value DECIMAL(28,10) NULL, text_value NVARCHAR(MAX) NULL, boolean_value BIT NULL, source_record_id BIGINT NOT NULL, valid_from DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), valid_to DATETIME2 NULL, is_current BIT NOT NULL DEFAULT 1, CONSTRAINT fk_observation_series FOREIGN KEY(series_id) REFERENCES [statistics].series(series_id), CONSTRAINT fk_observation_source FOREIGN KEY(source_record_id) REFERENCES raw.source_record(source_record_id));
IF OBJECT_ID(N'statistics.observation_dimension',N'U') IS NULL CREATE TABLE [statistics].observation_dimension (observation_id BIGINT NOT NULL, dimension_id BIGINT NOT NULL, classification_item_id BIGINT NULL, scalar_code NVARCHAR(255) NULL, CONSTRAINT pk_observation_dimension PRIMARY KEY(observation_id,dimension_id), CONSTRAINT fk_observation_dimension_observation FOREIGN KEY(observation_id) REFERENCES [statistics].observation(observation_id));
IF OBJECT_ID(N'statistics.observation_attribute',N'U') IS NULL CREATE TABLE [statistics].observation_attribute (observation_id BIGINT NOT NULL, attribute_code NVARCHAR(128) NOT NULL, value_json NVARCHAR(MAX) NOT NULL, CONSTRAINT pk_observation_attribute PRIMARY KEY(observation_id,attribute_code), CONSTRAINT fk_observation_attribute_observation FOREIGN KEY(observation_id) REFERENCES [statistics].observation(observation_id));
IF OBJECT_ID(N'reference.classification_item_snapshot',N'U') IS NULL CREATE TABLE reference.classification_item_snapshot (snapshot_id BIGINT NOT NULL, classification_item_id BIGINT NOT NULL, scheme_version_id BIGINT NOT NULL, code NVARCHAR(128) NOT NULL, label_ka NVARCHAR(255) NOT NULL, label_en NVARCHAR(255) NULL, parent_item_id BIGINT NULL, status VARCHAR(24) NOT NULL, CONSTRAINT pk_classification_item_snapshot PRIMARY KEY(snapshot_id,classification_item_id), CONSTRAINT fk_classification_snapshot FOREIGN KEY(snapshot_id) REFERENCES publication.snapshot(snapshot_id));
IF OBJECT_ID(N'geo.feature',N'U') IS NULL CREATE TABLE geo.feature (feature_id BIGINT IDENTITY PRIMARY KEY, dataset_snapshot_id BIGINT NOT NULL, feature_key NVARCHAR(512) NULL, geometry_geojson NVARCHAR(MAX) NOT NULL, geometry_type VARCHAR(32) NOT NULL, bbox NVARCHAR(255) NULL, source_record_id BIGINT NOT NULL, is_current BIT NOT NULL DEFAULT 1, CONSTRAINT fk_geo_source FOREIGN KEY(source_record_id) REFERENCES raw.source_record(source_record_id));
IF OBJECT_ID(N'geo.feature_link',N'U') IS NULL CREATE TABLE geo.feature_link (feature_id BIGINT NOT NULL, entity_id BIGINT NULL, classification_item_id BIGINT NULL, relationship_type_id BIGINT NOT NULL, CONSTRAINT pk_geo_feature_link PRIMARY KEY(feature_id,relationship_type_id), CONSTRAINT fk_geo_link_feature FOREIGN KEY(feature_id) REFERENCES geo.feature(feature_id));
IF OBJECT_ID(N'serving.metric_cache',N'U') IS NULL CREATE TABLE serving.metric_cache (cache_id BIGINT IDENTITY PRIMARY KEY, snapshot_id BIGINT NOT NULL, metric_id BIGINT NOT NULL, dimension_signature CHAR(64) NOT NULL, period_start DATE NULL, period_end DATE NULL, aggregate_value DECIMAL(28,10) NULL, refreshed_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT uq_metric_cache UNIQUE(snapshot_id,metric_id,dimension_signature,period_start,period_end), CONSTRAINT fk_metric_cache_snapshot FOREIGN KEY(snapshot_id) REFERENCES publication.snapshot(snapshot_id));
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'ix_staged_row_load' AND object_id=OBJECT_ID(N'ingest.staged_row')) CREATE INDEX ix_staged_row_load ON ingest.staged_row(dataset_load_id,validation_status,source_row_number);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'ix_validation_issue_row' AND object_id=OBJECT_ID(N'ingest.validation_issue')) CREATE INDEX ix_validation_issue_row ON ingest.validation_issue(staged_row_id,severity,rule_code);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'ix_dataset_snapshot_status' AND object_id=OBJECT_ID(N'publication.dataset_snapshot')) CREATE INDEX ix_dataset_snapshot_status ON publication.dataset_snapshot(dataset_version_id,status,dataset_snapshot_id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'ix_raw_snapshot' AND object_id=OBJECT_ID(N'raw.source_record')) CREATE INDEX ix_raw_snapshot ON raw.source_record(dataset_snapshot_id,source_key);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'ix_entity_snapshot' AND object_id=OBJECT_ID(N'entity.entity_record')) CREATE INDEX ix_entity_snapshot ON entity.entity_record(dataset_snapshot_id,external_key,is_current);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'ix_entity_link_from' AND object_id=OBJECT_ID(N'entity.entity_link')) CREATE INDEX ix_entity_link_from ON entity.entity_link(from_entity_id,relationship_type_id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'ix_series_metric' AND object_id=OBJECT_ID(N'statistics.series')) CREATE INDEX ix_series_metric ON [statistics].series(metric_id,series_key_hash,dataset_snapshot_id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'ix_observation_series_period' AND object_id=OBJECT_ID(N'statistics.observation')) CREATE INDEX ix_observation_series_period ON [statistics].observation(series_id,period_start,is_current);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'ix_observation_dimension_lookup' AND object_id=OBJECT_ID(N'statistics.observation_dimension')) CREATE INDEX ix_observation_dimension_lookup ON [statistics].observation_dimension(dimension_id,classification_item_id,observation_id);

/* Published data is immutable at the database boundary, not merely by application convention. */
IF OBJECT_ID(N'raw.tr_raw_source_record_published_immutable',N'TR') IS NULL EXEC(N'
CREATE TRIGGER raw.tr_raw_source_record_published_immutable ON raw.source_record AFTER UPDATE, DELETE AS
BEGIN
  SET NOCOUNT ON;
  IF EXISTS (SELECT 1 FROM inserted i JOIN publication.dataset_snapshot s ON s.dataset_snapshot_id=i.dataset_snapshot_id WHERE s.status=''PUBLISHED'')
     OR EXISTS (SELECT 1 FROM deleted d JOIN publication.dataset_snapshot s ON s.dataset_snapshot_id=d.dataset_snapshot_id WHERE s.status=''PUBLISHED'')
    THROW 51001, ''Published raw source records are immutable.'', 1;
END');
IF OBJECT_ID(N'entity.tr_entity_record_published_immutable',N'TR') IS NULL EXEC(N'
CREATE TRIGGER entity.tr_entity_record_published_immutable ON entity.entity_record AFTER UPDATE, DELETE AS
BEGIN
  SET NOCOUNT ON;
  IF EXISTS (SELECT 1 FROM inserted i JOIN publication.dataset_snapshot s ON s.dataset_snapshot_id=i.dataset_snapshot_id WHERE s.status=''PUBLISHED'')
     OR EXISTS (SELECT 1 FROM deleted d JOIN publication.dataset_snapshot s ON s.dataset_snapshot_id=d.dataset_snapshot_id WHERE s.status=''PUBLISHED'')
    THROW 51002, ''Published entity records are immutable.'', 1;
END');
IF OBJECT_ID(N'geo.tr_geo_feature_published_immutable',N'TR') IS NULL EXEC(N'
CREATE TRIGGER geo.tr_geo_feature_published_immutable ON geo.feature AFTER UPDATE, DELETE AS
BEGIN
  SET NOCOUNT ON;
  IF EXISTS (SELECT 1 FROM inserted i JOIN publication.dataset_snapshot s ON s.dataset_snapshot_id=i.dataset_snapshot_id WHERE s.status=''PUBLISHED'')
     OR EXISTS (SELECT 1 FROM deleted d JOIN publication.dataset_snapshot s ON s.dataset_snapshot_id=d.dataset_snapshot_id WHERE s.status=''PUBLISHED'')
    THROW 51003, ''Published geographic features are immutable.'', 1;
END');
IF OBJECT_ID(N'statistics.tr_observation_published_immutable',N'TR') IS NULL EXEC(N'
CREATE TRIGGER [statistics].tr_observation_published_immutable ON [statistics].observation AFTER UPDATE, DELETE AS
BEGIN
  SET NOCOUNT ON;
  IF EXISTS (SELECT 1 FROM inserted i JOIN [statistics].series x ON x.series_id=i.series_id JOIN publication.dataset_snapshot s ON s.dataset_snapshot_id=x.dataset_snapshot_id WHERE s.status=''PUBLISHED'')
     OR EXISTS (SELECT 1 FROM deleted d JOIN [statistics].series x ON x.series_id=d.series_id JOIN publication.dataset_snapshot s ON s.dataset_snapshot_id=x.dataset_snapshot_id WHERE s.status=''PUBLISHED'')
    THROW 51004, ''Published observations are immutable.'', 1;
END');
