/* Run in geostat-archive. Retention is one year; immutable metadata remains in Control Plane. */
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'archive') EXEC(N'CREATE SCHEMA archive');
IF OBJECT_ID(N'archive.snapshot',N'U') IS NULL CREATE TABLE archive.snapshot (archive_snapshot_id BIGINT IDENTITY PRIMARY KEY, product_id BIGINT NOT NULL, original_snapshot_id BIGINT NOT NULL, archived_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), purge_after DATETIME2 NOT NULL, checksum CHAR(64) NOT NULL, status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE');
IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE name=N'uq_archive_original_snapshot') ALTER TABLE archive.snapshot ADD CONSTRAINT uq_archive_original_snapshot UNIQUE(product_id,original_snapshot_id);
IF OBJECT_ID(N'archive.record',N'U') IS NULL CREATE TABLE archive.record (archive_record_id BIGINT IDENTITY PRIMARY KEY, archive_snapshot_id BIGINT NOT NULL, dataset_version_id BIGINT NOT NULL, original_source_record_id BIGINT NOT NULL, record_kind VARCHAR(32) NOT NULL, source_key NVARCHAR(512) NULL, payload_json NVARCHAR(MAX) NOT NULL, payload_hash CHAR(64) NOT NULL, CONSTRAINT uq_archive_original_record UNIQUE(archive_snapshot_id,original_source_record_id), CONSTRAINT fk_archive_record_snapshot FOREIGN KEY(archive_snapshot_id) REFERENCES archive.snapshot(archive_snapshot_id));
IF COL_LENGTH(N'archive.record', N'original_source_record_id') IS NULL ALTER TABLE archive.record ADD original_source_record_id BIGINT NULL;
IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE name=N'uq_archive_original_record') ALTER TABLE archive.record ADD CONSTRAINT uq_archive_original_record UNIQUE(archive_snapshot_id,original_source_record_id);
IF OBJECT_ID(N'archive.artifact_reference',N'U') IS NULL CREATE TABLE archive.artifact_reference (archive_artifact_id BIGINT IDENTITY PRIMARY KEY, archive_snapshot_id BIGINT NOT NULL, object_uri NVARCHAR(2048) NOT NULL, checksum CHAR(64) NOT NULL, original_name NVARCHAR(512) NOT NULL, CONSTRAINT fk_archive_artifact_snapshot FOREIGN KEY(archive_snapshot_id) REFERENCES archive.snapshot(archive_snapshot_id));
IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE name=N'uq_archive_artifact_reference') ALTER TABLE archive.artifact_reference ADD CONSTRAINT uq_archive_artifact_reference UNIQUE(archive_snapshot_id,object_uri);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'ix_archive_snapshot_purge' AND object_id=OBJECT_ID(N'archive.snapshot')) CREATE INDEX ix_archive_snapshot_purge ON archive.snapshot(purge_after,status);
