/*
 * KIDS_PORTAL_V1 revision 7 — delegated, evidence-based statistical semantics.
 * Revision 6 stays immutable and executable. No observation value is seeded here.
 */
IF OBJECT_ID(N'platform.statistical_unit',N'U') IS NULL CREATE TABLE platform.statistical_unit(
 unit_id BIGINT IDENTITY PRIMARY KEY,unit_code NVARCHAR(120) NOT NULL UNIQUE,quantity_kind VARCHAR(24) NOT NULL,
 scale_factor DECIMAL(28,10) NOT NULL,denominator_text NVARCHAR(500) NULL,title NVARCHAR(255) NOT NULL,status VARCHAR(24) NOT NULL
);
IF OBJECT_ID(N'platform.data_quality_policy',N'U') IS NULL CREATE TABLE platform.data_quality_policy(
 quality_policy_id BIGINT IDENTITY PRIMARY KEY,policy_code NVARCHAR(120) NOT NULL UNIQUE,status VARCHAR(24) NOT NULL,rules_json NVARCHAR(MAX) NOT NULL,
 CONSTRAINT ck_data_quality_policy_json CHECK(ISJSON(rules_json)=1)
);
IF OBJECT_ID(N'platform.confidentiality_policy',N'U') IS NULL CREATE TABLE platform.confidentiality_policy(
 confidentiality_policy_id BIGINT IDENTITY PRIMARY KEY,policy_code NVARCHAR(120) NOT NULL UNIQUE,status VARCHAR(24) NOT NULL,rules_json NVARCHAR(MAX) NOT NULL,
 CONSTRAINT ck_confidentiality_policy_json CHECK(ISJSON(rules_json)=1)
);
IF OBJECT_ID(N'platform.metric_semantic_profile',N'U') IS NULL CREATE TABLE platform.metric_semantic_profile(
 metric_semantic_profile_id BIGINT IDENTITY PRIMARY KEY,metric_id BIGINT NOT NULL UNIQUE,source_resource_external_key NVARCHAR(255) NOT NULL,
 unit_id BIGINT NOT NULL,inference_method VARCHAR(48) NOT NULL,inference_confidence DECIMAL(5,4) NOT NULL,inference_rationale NVARCHAR(1000) NOT NULL,
 approved_basis NVARCHAR(255) NOT NULL,status VARCHAR(24) NOT NULL,
 CONSTRAINT fk_metric_semantic_profile_metric FOREIGN KEY(metric_id) REFERENCES platform.metric(metric_id),
 CONSTRAINT fk_metric_semantic_profile_unit FOREIGN KEY(unit_id) REFERENCES platform.statistical_unit(unit_id),
 CONSTRAINT ck_metric_semantic_confidence CHECK(inference_confidence BETWEEN 0 AND 1)
);
IF OBJECT_ID(N'platform.statistical_semantic_binding',N'U') IS NULL CREATE TABLE platform.statistical_semantic_binding(
 statistical_semantic_binding_id BIGINT IDENTITY PRIMARY KEY,dataflow_id BIGINT NOT NULL,carrier_external_code NVARCHAR(255) NOT NULL,
 metric_id BIGINT NOT NULL,unit_id BIGINT NOT NULL,aggregation VARCHAR(24) NOT NULL,obs_status VARCHAR(8) NOT NULL,conf_status VARCHAR(8) NOT NULL,
 quality_policy_id BIGINT NOT NULL,confidentiality_policy_id BIGINT NOT NULL,status VARCHAR(24) NOT NULL,
 CONSTRAINT uq_statistical_semantic_binding UNIQUE(dataflow_id,carrier_external_code),
 CONSTRAINT fk_stat_semantic_dataflow FOREIGN KEY(dataflow_id) REFERENCES platform.statistical_dataflow(dataflow_id),
 CONSTRAINT fk_stat_semantic_metric FOREIGN KEY(metric_id) REFERENCES platform.metric(metric_id),
 CONSTRAINT fk_stat_semantic_unit FOREIGN KEY(unit_id) REFERENCES platform.statistical_unit(unit_id),
 CONSTRAINT fk_stat_semantic_quality FOREIGN KEY(quality_policy_id) REFERENCES platform.data_quality_policy(quality_policy_id),
 CONSTRAINT fk_stat_semantic_confidentiality FOREIGN KEY(confidentiality_policy_id) REFERENCES platform.confidentiality_policy(confidentiality_policy_id)
);

MERGE platform.statistical_unit t USING(VALUES
(N'COUNT_EVENT','EVENT',1,NULL,N'Count of events'),(N'COUNT_CASE','CASE',1,NULL,N'Count of cases'),(N'PERSON','PERSON',1,NULL,N'Persons'),
(N'THOUSAND_PERSONS','PERSON',1000,NULL,N'Thousand persons'),(N'THOUSAND_VISITS','VISIT',1000,NULL,N'Thousand visits'),
(N'AVERAGE_NIGHTS','NIGHT',1,N'per visit',N'Average nights per visit'),(N'PER_100000_LIVE_BIRTHS','RATIO',1,N'100,000 live births',N'Per 100,000 live births'),
(N'PER_1000_UNINFECTED_POPULATION','RATIO',1,N'1,000 uninfected population',N'Per 1,000 uninfected population'),
(N'PER_100000_POPULATION','RATIO',1,N'100,000 population',N'Per 100,000 population'),(N'PERCENT','RATIO',0.01,N'100 population',N'Percent')
)s(code,kind,scale,denominator,title) ON t.unit_code=s.code
WHEN MATCHED THEN UPDATE SET quantity_kind=s.kind,scale_factor=s.scale,denominator_text=s.denominator,title=s.title,status='PROVISIONAL_APPROVED'
WHEN NOT MATCHED THEN INSERT(unit_code,quantity_kind,scale_factor,denominator_text,title,status)VALUES(s.code,s.kind,s.scale,s.denominator,s.title,'PROVISIONAL_APPROVED');

MERGE platform.data_quality_policy t USING(VALUES(N'KIDS_AGGREGATE_QUALITY_V1',N'{"period":{"required":true,"pattern":"^[0-9]{4}$"},"dimension":{"required":true,"publishedAliasRequired":true},"value":{"numericRequired":true,"finite":true,"minimum":0},"percent":{"minimum":0,"maximum":100},"counts":{"integerExpected":true},"duplicates":"REJECT_BY_CARRIER_PERIOD_AGE","overlappingAgeGroups":true,"crossAgeAggregation":"FORBIDDEN","sourceLineageRequired":true}'))s(code,rules) ON t.policy_code=s.code
WHEN MATCHED THEN UPDATE SET status='PROVISIONAL_APPROVED',rules_json=s.rules WHEN NOT MATCHED THEN INSERT(policy_code,status,rules_json)VALUES(s.code,'PROVISIONAL_APPROVED',s.rules);
MERGE platform.confidentiality_policy t USING(VALUES(N'KIDS_PUBLIC_AGGREGATE_V1',N'{"dataClass":"PUBLIC_AGGREGATE","containsMicrodata":false,"containsDirectIdentifier":false,"sourcePublicationPreserved":true,"smallCountThreshold":5,"smallCountAction":"FLAG_FOR_REVIEW_NO_AUTOMATIC_REWRITE","defaultConfStatus":"F","publicationScope":"PUBLIC"}'))s(code,rules) ON t.policy_code=s.code
WHEN MATCHED THEN UPDATE SET status='PROVISIONAL_APPROVED',rules_json=s.rules WHEN NOT MATCHED THEN INSERT(policy_code,status,rules_json)VALUES(s.code,'PROVISIONAL_APPROVED',s.rules);

DECLARE @product BIGINT=(SELECT product_id FROM platform.data_product WHERE product_code=N'KIDS_PORTAL');
DECLARE @contract BIGINT=(SELECT contract_id FROM platform.ingestion_contract WHERE contract_code=N'KIDS_PORTAL_V1');
DECLARE @resourceDataset BIGINT=(SELECT dataset_id FROM platform.dataset WHERE product_id=@product AND dataset_code=N'KIDS_RESOURCE');
DECLARE @measure BIGINT=(SELECT measure_id FROM platform.measure WHERE measure_code=N'KIDS_OBS_VALUE_INPUT');
DECLARE @dataflow BIGINT=(SELECT dataflow_id FROM platform.statistical_dataflow WHERE product_id=@product AND dataflow_code=N'KIDS_FILES_STATISTICS');
IF @product IS NULL OR @contract IS NULL OR @resourceDataset IS NULL OR @measure IS NULL OR @dataflow IS NULL THROW 51000,'KIDS revision-7 prerequisites are missing',1;

DECLARE @semantic TABLE(resource_key NVARCHAR(20),metric_code NVARCHAR(120),unit_code NVARCHAR(120),confidence DECIMAL(5,4),rationale NVARCHAR(1000));
INSERT @semantic VALUES
(N'162',N'KIDS_ABORTIONS_COUNT',N'COUNT_EVENT',.99,N'Title explicitly states number of abortions'),(N'163',N'KIDS_MALIGNANT_NEOPLASM_NEW_CASES',N'COUNT_CASE',.99,N'Title explicitly states new cases'),(N'164',N'KIDS_SEXUALLY_TRANSMITTED_DISEASE_NEW_CASES',N'COUNT_CASE',.99,N'Title explicitly states new cases'),(N'165',N'KIDS_DIABETES_MELLITUS_NEW_CASES',N'COUNT_CASE',.99,N'Title explicitly states new cases'),
(N'166',N'KIDS_RESPIRATORY_TUBERCULOSIS_CASES',N'COUNT_CASE',.98,N'Title states number of disease cases'),(N'167',N'KIDS_TUBERCULOUS_MENINGITIS_CASES',N'COUNT_CASE',.98,N'Title states number of disease cases'),(N'168',N'KIDS_MUSCULOSKELETAL_TUBERCULOSIS_CASES',N'COUNT_CASE',.98,N'Title states number of disease cases'),(N'169',N'KIDS_INFECTIOUS_PARASITIC_DISEASE_NEW_CASES',N'COUNT_CASE',.99,N'Title explicitly states new cases'),
(N'170',N'KIDS_BLOOD_DISEASE_NEW_CASES',N'COUNT_CASE',.99,N'Title explicitly states new cases'),(N'171',N'KIDS_ENDOCRINE_METABOLIC_DISEASE_NEW_CASES',N'COUNT_CASE',.98,N'Title explicitly states new cases'),(N'172',N'KIDS_MENTAL_BEHAVIOURAL_DISORDER_NEW_CASES',N'COUNT_CASE',.99,N'Title explicitly states new cases'),(N'173',N'KIDS_NERVOUS_SYSTEM_DISEASE_NEW_CASES',N'COUNT_CASE',.99,N'Title explicitly states new cases'),
(N'174',N'KIDS_EYE_ADNEXA_DISEASE_NEW_CASES',N'COUNT_CASE',.99,N'Title explicitly states new cases'),(N'175',N'KIDS_EAR_MASTOID_DISEASE_NEW_CASES',N'COUNT_CASE',.99,N'Title explicitly states new cases'),(N'176',N'KIDS_CIRCULATORY_DISEASE_NEW_CASES',N'COUNT_CASE',.99,N'Title explicitly states new cases'),(N'177',N'KIDS_RESPIRATORY_DISEASE_NEW_CASES',N'COUNT_CASE',.99,N'Title explicitly states new cases'),
(N'178',N'KIDS_DIGESTIVE_DISEASE_NEW_CASES',N'COUNT_CASE',.99,N'Title explicitly states new cases'),(N'179',N'KIDS_SKIN_SUBCUTANEOUS_DISEASE_NEW_CASES',N'COUNT_CASE',.99,N'Title explicitly states new cases'),(N'180',N'KIDS_MUSCULOSKELETAL_DISEASE_NEW_CASES',N'COUNT_CASE',.99,N'Title explicitly states new cases'),(N'181',N'KIDS_UROGENITAL_DISEASE_NEW_CASES',N'COUNT_CASE',.99,N'Title explicitly states new cases'),(N'183',N'KIDS_CONGENITAL_MALFORMATION_NEW_CASES',N'COUNT_CASE',.99,N'Title explicitly states new cases'),
(N'297',N'KIDS_DISABILITY_SOCIAL_PACKAGE_RECIPIENTS',N'PERSON',.98,N'Title states number of persons'),(N'299',N'KIDS_SURVIVOR_SOCIAL_PACKAGE_RECIPIENTS',N'PERSON',.95,N'Title identifies recipients by age'),(N'301',N'KIDS_SUBSISTENCE_ALLOWANCE_BENEFICIARIES',N'PERSON',.99,N'Title states number of beneficiaries'),(N'303',N'KIDS_PLANNED_OUTPATIENT_REGISTERED_PERSONS',N'PERSON',.99,N'Title states number of registered persons'),
(N'305',N'KIDS_CHRONIC_MEDICINE_PROGRAM_BENEFICIARIES',N'PERSON',.99,N'Title states number of beneficiaries'),(N'306',N'KIDS_ADOPTED_CHILDREN',N'PERSON',.99,N'Title counts adopted children'),(N'308',N'KIDS_CHILDREN_GRANTED_ADOPTION_STATUS',N'PERSON',.96,N'Title and integer values indicate children granted status'),(N'310',N'KIDS_INTERNALLY_DISPLACED_PERSONS',N'PERSON',.99,N'Title states number of persons'),
(N'373',N'KIDS_LABOUR_FORCE_POPULATION',N'THOUSAND_PERSONS',.85,N'Magnitude and source workbook identify labour-force population in thousands'),(N'385',N'KIDS_RESIDENT_VISITORS_MONTHLY_AVERAGE',N'THOUSAND_PERSONS',.99,N'Title explicitly states thousand visitors'),(N'386',N'KIDS_DOMESTIC_VISITS_MONTHLY_AVERAGE',N'THOUSAND_VISITS',.99,N'Title explicitly states thousand visits'),(N'387',N'KIDS_AVERAGE_NIGHTS_PER_VISIT',N'AVERAGE_NIGHTS',.99,N'Title explicitly states average number of nights'),
(N'404',N'KIDS_MATERNAL_MORTALITY_RATIO',N'PER_100000_LIVE_BIRTHS',.99,N'Title explicitly gives denominator'),(N'407',N'KIDS_HIV_INCIDENCE_RATE',N'PER_1000_UNINFECTED_POPULATION',.99,N'Title explicitly gives denominator'),(N'409',N'KIDS_ANAEMIA_PREVALENCE',N'PERCENT',.95,N'Prevalence values and SDG convention imply percent'),(N'417',N'KIDS_SUICIDES_COUNT',N'COUNT_EVENT',.99,N'Title and integral values identify event counts'),(N'418',N'KIDS_SUICIDE_MORTALITY_RATE',N'PER_100000_POPULATION',.97,N'SDG 3.4.2 is defined per 100,000 population'),
(N'438',N'KIDS_DAILY_INTERNET_USE_SHARE',N'PERCENT',.99,N'Title states population share'),(N'439',N'KIDS_RECENT_COMPUTER_USE_SHARE',N'PERCENT',.99,N'Title states population share'),(N'440',N'KIDS_MOBILE_PHONE_USE_SHARE',N'PERCENT',.99,N'Title states population share'),(N'451',N'KIDS_LITERACY_RATE',N'PERCENT',.99,N'Title states rate and values are percentages'),(N'452',N'KIDS_EARLY_EDUCATION_LEAVERS_RATE',N'PERCENT',.97,N'Indicator convention and 0-100 values imply percent');

INSERT platform.metric(metric_code,source_dataset_id,measure_id,aggregation,allowed_dimension_set_json,status)
SELECT s.metric_code,@resourceDataset,@measure,'NONE',N'["TIME_PERIOD","AGE_GROUP"]','PROVISIONAL_APPROVED' FROM @semantic s
WHERE NOT EXISTS(SELECT 1 FROM platform.metric m WHERE m.metric_code=s.metric_code);
MERGE platform.metric_semantic_profile t USING(SELECT m.metric_id,s.resource_key,u.unit_id,s.confidence,s.rationale FROM @semantic s JOIN platform.metric m ON m.metric_code=s.metric_code JOIN platform.statistical_unit u ON u.unit_code=s.unit_code)s
ON t.metric_id=s.metric_id WHEN MATCHED THEN UPDATE SET source_resource_external_key=s.resource_key,unit_id=s.unit_id,inference_method='TITLE_RANGE_STANDARD_INFERENCE',inference_confidence=s.confidence,inference_rationale=s.rationale,approved_basis=N'DELEGATED_OWNER_AUTHORIZATION_2026_09_10',status='PROVISIONAL_APPROVED'
WHEN NOT MATCHED THEN INSERT(metric_id,source_resource_external_key,unit_id,inference_method,inference_confidence,inference_rationale,approved_basis,status)VALUES(s.metric_id,s.resource_key,s.unit_id,'TITLE_RANGE_STANDARD_INFERENCE',s.confidence,s.rationale,N'DELEGATED_OWNER_AUTHORIZATION_2026_09_10','PROVISIONAL_APPROVED');
DECLARE @quality BIGINT=(SELECT quality_policy_id FROM platform.data_quality_policy WHERE policy_code=N'KIDS_AGGREGATE_QUALITY_V1'),@conf BIGINT=(SELECT confidentiality_policy_id FROM platform.confidentiality_policy WHERE policy_code=N'KIDS_PUBLIC_AGGREGATE_V1');
MERGE platform.statistical_semantic_binding t USING(SELECT @dataflow dataflow_id,CONCAT(N'CARRIER|',s.resource_key) carrier,m.metric_id,u.unit_id FROM @semantic s JOIN platform.metric m ON m.metric_code=s.metric_code JOIN platform.statistical_unit u ON u.unit_code=s.unit_code)s
ON t.dataflow_id=s.dataflow_id AND t.carrier_external_code=s.carrier WHEN MATCHED THEN UPDATE SET metric_id=s.metric_id,unit_id=s.unit_id,aggregation='NONE',obs_status='A',conf_status='F',quality_policy_id=@quality,confidentiality_policy_id=@conf,status='PROVISIONAL_APPROVED'
WHEN NOT MATCHED THEN INSERT(dataflow_id,carrier_external_code,metric_id,unit_id,aggregation,obs_status,conf_status,quality_policy_id,confidentiality_policy_id,status)VALUES(s.dataflow_id,s.carrier,s.metric_id,s.unit_id,'NONE','A','F',@quality,@conf,'PROVISIONAL_APPROVED');

/* DSD revision 2 binds metric/unit/policy semantics without changing observation values. */
IF NOT EXISTS(SELECT 1 FROM platform.statistical_dsd WHERE dataflow_id=@dataflow AND dsd_code=N'KIDS_FILES_STATISTICS_DSD' AND revision=2)
 INSERT platform.statistical_dsd(dataflow_id,dsd_code,revision,observation_grain,status,valid_from)VALUES(@dataflow,N'KIDS_FILES_STATISTICS_DSD',2,N'carrier_code + cell_ordinal','PROVISIONAL_APPROVED','2026-09-10');
DECLARE @oldDsd BIGINT=(SELECT dsd_id FROM platform.statistical_dsd WHERE dataflow_id=@dataflow AND dsd_code=N'KIDS_FILES_STATISTICS_DSD' AND revision=1),@newDsd BIGINT=(SELECT dsd_id FROM platform.statistical_dsd WHERE dataflow_id=@dataflow AND dsd_code=N'KIDS_FILES_STATISTICS_DSD' AND revision=2);
INSERT platform.statistical_component(dsd_id,component_code,component_role,component_order,required,dimension_id,measure_id,classification_version_id,attachment_level,source_field,normalized_field,constraint_json,status)
SELECT @newDsd,component_code,component_role,component_order,required,dimension_id,measure_id,classification_version_id,attachment_level,source_field,normalized_field,constraint_json,'PROVISIONAL_APPROVED' FROM platform.statistical_component c WHERE c.dsd_id=@oldDsd AND NOT EXISTS(SELECT 1 FROM platform.statistical_component x WHERE x.dsd_id=@newDsd AND x.component_code=c.component_code);

/* Revision 7 extends the r6 site contract with units, metrics and carrier bindings. */
DECLARE @doc NVARCHAR(MAX)=N'{"contract":"KIDS_PORTAL_V1","revision":7,"parent":6,"compatibility":"BACKWARD_COMPATIBLE","accessProfile":"ACCESS_CANONICAL_R7_SEMANTIC","datasets":15,"fields":104,"relations":21,"semanticBindings":43,"aggregation":"NONE","qualityPolicy":"KIDS_AGGREGATE_QUALITY_V1","confidentialityPolicy":"KIDS_PUBLIC_AGGREGATE_V1"}';
DECLARE @parent BIGINT=(SELECT site_contract_revision_id FROM platform.site_contract_revision WHERE contract_code=N'KIDS_PORTAL_V1' AND revision=6);
IF NOT EXISTS(SELECT 1 FROM platform.site_contract_revision WHERE contract_code=N'KIDS_PORTAL_V1' AND revision=7) INSERT platform.site_contract_revision(product_id,contract_code,revision,parent_revision_id,schema_standard,compatibility_mode,status,contract_checksum,contract_document_json)VALUES(@product,N'KIDS_PORTAL_V1',7,@parent,N'ISO/IEC 11179 + SDMX information model',N'BACKWARD_COMPATIBLE','APPROVED',CONVERT(VARCHAR(64),HASHBYTES('SHA2_256',CONVERT(VARBINARY(MAX),@doc)),2),@doc);
DECLARE @site7 BIGINT=(SELECT site_contract_revision_id FROM platform.site_contract_revision WHERE contract_code=N'KIDS_PORTAL_V1' AND revision=7);

IF NOT EXISTS(SELECT 1 FROM platform.site_contract_node WHERE site_contract_revision_id=@site7 AND node_code=N'KIDS_ROOT')INSERT platform.site_contract_node(site_contract_revision_id,node_code,node_kind,path_segment,sort_order,title_ka,title_en)VALUES(@site7,N'KIDS_ROOT','SITE_ROOT',N'kids',1,N'ბავშვებისა და მოზარდების სტატისტიკა',N'Children and youth statistics');
DECLARE @root7 BIGINT=(SELECT node_id FROM platform.site_contract_node WHERE site_contract_revision_id=@site7 AND node_code=N'KIDS_ROOT');
INSERT platform.site_contract_node(site_contract_revision_id,node_code,parent_node_id,node_kind,dataset_code,path_segment,sort_order,title_ka,title_en)
SELECT @site7,v.code,@root7,v.kind,v.dataset,v.path,v.ord,v.ka,v.en FROM(VALUES
(N'KIDS_GOALS','ENTITY_COLLECTION',N'KIDS_GOAL',N'goals',10,N'მიზნები',N'Goals'),(N'KIDS_RESOURCES','ENTITY_COLLECTION',N'KIDS_RESOURCE',N'resources',20,N'რესურსები',N'Resources'),(N'KIDS_GLOSSARY','ENTITY_COLLECTION',N'KIDS_GLOSSARY_ENTRY',N'glossary',30,N'ლექსიკონი',N'Glossary'),(N'KIDS_STATISTICS','STATISTICAL_DATAFLOW',N'KIDS_STATISTICAL_INPUT',N'statistics',40,N'სტატისტიკა',N'Statistics'),(N'KIDS_CLASSIFIERS','REFERENCE_REGISTRY',N'KIDS_CLASSIFIER_ITEM',N'classifiers',50,N'კლასიფიკატორები',N'Classifiers'))v(code,kind,dataset,path,ord,ka,en) WHERE NOT EXISTS(SELECT 1 FROM platform.site_contract_node n WHERE n.site_contract_revision_id=@site7 AND n.node_code=v.code);

INSERT platform.site_contract_dataset(site_contract_revision_id,dataset_version_id,dataset_code,access_table_name,data_family,business_grain,natural_key_expression,row_role,load_order,required)
SELECT @site7,dataset_version_id,dataset_code,access_table_name,data_family,business_grain,natural_key_expression,row_role,load_order,required FROM platform.site_contract_dataset d WHERE d.site_contract_revision_id=@parent AND NOT EXISTS(SELECT 1 FROM platform.site_contract_dataset x WHERE x.site_contract_revision_id=@site7 AND x.dataset_code=d.dataset_code);
INSERT platform.site_contract_field(contract_dataset_id,field_name,logical_type,semantic_role,ordinal,required,key_role,classifier_scheme_code,source_expression,normalization_rule)
SELECT target.contract_dataset_id,f.field_name,f.logical_type,f.semantic_role,f.ordinal,f.required,f.key_role,f.classifier_scheme_code,f.source_expression,f.normalization_rule FROM platform.site_contract_field f JOIN platform.site_contract_dataset source ON source.contract_dataset_id=f.contract_dataset_id AND source.site_contract_revision_id=@parent JOIN platform.site_contract_dataset target ON target.site_contract_revision_id=@site7 AND target.dataset_code=source.dataset_code WHERE NOT EXISTS(SELECT 1 FROM platform.site_contract_field x WHERE x.contract_dataset_id=target.contract_dataset_id AND x.field_name=f.field_name);
INSERT platform.site_contract_relation(site_contract_revision_id,relation_code,from_dataset_code,from_field_name,to_dataset_code,to_field_name,relation_kind,cardinality,required,enforcement_policy,load_priority)
SELECT @site7,relation_code,from_dataset_code,from_field_name,to_dataset_code,to_field_name,relation_kind,cardinality,required,enforcement_policy,load_priority FROM platform.site_contract_relation r WHERE r.site_contract_revision_id=@parent AND NOT EXISTS(SELECT 1 FROM platform.site_contract_relation x WHERE x.site_contract_revision_id=@site7 AND x.relation_code=r.relation_code);
INSERT platform.site_contract_classifier(site_contract_revision_id,scheme_code,version_policy,authority_mode,unknown_value_policy,publication_policy)
SELECT @site7,scheme_code,version_policy,authority_mode,unknown_value_policy,publication_policy FROM platform.site_contract_classifier c WHERE c.site_contract_revision_id=@parent AND NOT EXISTS(SELECT 1 FROM platform.site_contract_classifier x WHERE x.site_contract_revision_id=@site7 AND x.scheme_code=c.scheme_code);
INSERT platform.site_contract_gate(site_contract_revision_id,gate_code,gate_type,severity,blocking,rule_json)
SELECT @site7,gate_code,gate_type,severity,blocking,rule_json FROM platform.site_contract_gate g WHERE g.site_contract_revision_id=@parent AND NOT EXISTS(SELECT 1 FROM platform.site_contract_gate x WHERE x.site_contract_revision_id=@site7 AND x.gate_code=g.gate_code);

DECLARE @newSpec TABLE(code NVARCHAR(120),family VARCHAR(24),grain NVARCHAR(500),access_table NVARCHAR(128),natural_key NVARCHAR(1000),row_role VARCHAR(32),load_order INT);
INSERT @newSpec VALUES(N'KIDS_STATISTICAL_UNIT','REFERENCE',N'one governed statistical unit',N'__stat_unit',N'unit_code','REFERENCE',55),(N'KIDS_STATISTICAL_METRIC','REFERENCE',N'one carrier-specific governed metric',N'__stat_metric',N'metric_code','REFERENCE',56),(N'KIDS_STATISTICAL_SEMANTIC_BINDING','RELATION',N'one approved semantic binding per carrier',N'kids_statistical_semantic_binding',N'carrier_code','RELATION',145);
INSERT platform.dataset(product_id,dataset_code,dataset_family,business_grain,lifecycle_status)SELECT @product,s.code,s.family,s.grain,'PROVISIONAL_APPROVED' FROM @newSpec s WHERE NOT EXISTS(SELECT 1 FROM platform.dataset d WHERE d.product_id=@product AND d.dataset_code=s.code);
DECLARE @newCode NVARCHAR(120),@newDataset BIGINT;DECLARE new_cursor CURSOR LOCAL FAST_FORWARD FOR SELECT code FROM @newSpec;OPEN new_cursor;FETCH NEXT FROM new_cursor INTO @newCode;WHILE @@FETCH_STATUS=0 BEGIN SELECT @newDataset=dataset_id FROM platform.dataset WHERE product_id=@product AND dataset_code=@newCode;IF NOT EXISTS(SELECT 1 FROM platform.dataset_version WHERE dataset_id=@newDataset AND version=1)INSERT platform.dataset_version(dataset_id,version,status,effective_from)VALUES(@newDataset,1,'PROVISIONAL_APPROVED',SYSUTCDATETIME());FETCH NEXT FROM new_cursor INTO @newCode;END CLOSE new_cursor;DEALLOCATE new_cursor;
INSERT platform.site_contract_dataset(site_contract_revision_id,dataset_version_id,dataset_code,access_table_name,data_family,business_grain,natural_key_expression,row_role,load_order,required)
SELECT @site7,v.dataset_version_id,s.code,s.access_table,s.family,s.grain,s.natural_key,s.row_role,s.load_order,1 FROM @newSpec s JOIN platform.dataset d ON d.product_id=@product AND d.dataset_code=s.code JOIN platform.dataset_version v ON v.dataset_id=d.dataset_id AND v.version=1 WHERE NOT EXISTS(SELECT 1 FROM platform.site_contract_dataset x WHERE x.site_contract_revision_id=@site7 AND x.dataset_code=s.code);

DECLARE @fields TABLE(dataset_code NVARCHAR(120),ordinal INT,field_name NVARCHAR(128),logical_type VARCHAR(24),semantic_role VARCHAR(32),required BIT,key_role VARCHAR(24));
INSERT @fields VALUES
(N'KIDS_STATISTICAL_UNIT',1,N'unit_code','CODE','NATURAL_KEY',1,'NATURAL'),(N'KIDS_STATISTICAL_UNIT',2,N'quantity_kind','CODE','ATTRIBUTE',1,NULL),(N'KIDS_STATISTICAL_UNIT',3,N'scale_factor','DECIMAL','ATTRIBUTE',1,NULL),(N'KIDS_STATISTICAL_UNIT',4,N'denominator_text','TEXT','ATTRIBUTE',0,NULL),(N'KIDS_STATISTICAL_UNIT',5,N'title','TEXT','CONTENT',1,NULL),
(N'KIDS_STATISTICAL_METRIC',1,N'metric_code','CODE','NATURAL_KEY',1,'NATURAL'),(N'KIDS_STATISTICAL_METRIC',2,N'source_resource_id','CODE','FOREIGN_KEY',1,NULL),(N'KIDS_STATISTICAL_METRIC',3,N'title_ka','TEXT','LOCALIZED_TEXT',0,NULL),(N'KIDS_STATISTICAL_METRIC',4,N'title_en','TEXT','LOCALIZED_TEXT',0,NULL),(N'KIDS_STATISTICAL_METRIC',5,N'measure_component_code','CODE','ATTRIBUTE',1,NULL),(N'KIDS_STATISTICAL_METRIC',6,N'unit_code','CODE','FOREIGN_KEY',1,NULL),(N'KIDS_STATISTICAL_METRIC',7,N'aggregation','CODE','ATTRIBUTE',1,NULL),(N'KIDS_STATISTICAL_METRIC',8,N'lifecycle_state','CODE','ATTRIBUTE',1,NULL),(N'KIDS_STATISTICAL_METRIC',9,N'inference_confidence','DECIMAL','ATTRIBUTE',1,NULL),(N'KIDS_STATISTICAL_METRIC',10,N'inference_rationale','TEXT','ATTRIBUTE',1,NULL),
(N'KIDS_STATISTICAL_SEMANTIC_BINDING',1,N'carrier_code','CODE','NATURAL_KEY',1,'NATURAL'),(N'KIDS_STATISTICAL_SEMANTIC_BINDING',2,N'metric_code','CODE','FOREIGN_KEY',1,NULL),(N'KIDS_STATISTICAL_SEMANTIC_BINDING',3,N'unit_code','CODE','FOREIGN_KEY',1,NULL),(N'KIDS_STATISTICAL_SEMANTIC_BINDING',4,N'aggregation','CODE','ATTRIBUTE',1,NULL),(N'KIDS_STATISTICAL_SEMANTIC_BINDING',5,N'obs_status','CODE','ATTRIBUTE',1,NULL),(N'KIDS_STATISTICAL_SEMANTIC_BINDING',6,N'conf_status','CODE','ATTRIBUTE',1,NULL),(N'KIDS_STATISTICAL_SEMANTIC_BINDING',7,N'quality_policy_code','CODE','ATTRIBUTE',1,NULL),(N'KIDS_STATISTICAL_SEMANTIC_BINDING',8,N'confidentiality_policy_code','CODE','ATTRIBUTE',1,NULL),(N'KIDS_STATISTICAL_SEMANTIC_BINDING',9,N'inference_method','CODE','ATTRIBUTE',1,NULL),(N'KIDS_STATISTICAL_SEMANTIC_BINDING',10,N'operation','CODE','ATTRIBUTE',1,NULL);
INSERT platform.site_contract_field(contract_dataset_id,field_name,logical_type,semantic_role,ordinal,required,key_role)SELECT d.contract_dataset_id,f.field_name,f.logical_type,f.semantic_role,f.ordinal,f.required,f.key_role FROM @fields f JOIN platform.site_contract_dataset d ON d.site_contract_revision_id=@site7 AND d.dataset_code=f.dataset_code WHERE NOT EXISTS(SELECT 1 FROM platform.site_contract_field x WHERE x.contract_dataset_id=d.contract_dataset_id AND x.field_name=f.field_name);
DECLARE @relations TABLE(code NVARCHAR(120),fd NVARCHAR(120),ff NVARCHAR(128),td NVARCHAR(120),tf NVARCHAR(128),card VARCHAR(24),priority INT);INSERT @relations VALUES(N'METRIC_FOR_RESOURCE',N'KIDS_STATISTICAL_METRIC',N'source_resource_id',N'KIDS_RESOURCE',N'source_resource_id','ONE_TO_ONE',122),(N'METRIC_UNIT',N'KIDS_STATISTICAL_METRIC',N'unit_code',N'KIDS_STATISTICAL_UNIT',N'unit_code','MANY_TO_ONE',123),(N'SEMANTIC_FOR_CARRIER',N'KIDS_STATISTICAL_SEMANTIC_BINDING',N'carrier_code',N'KIDS_STATISTICAL_CARRIER',N'carrier_code','ONE_TO_ONE',146),(N'SEMANTIC_METRIC',N'KIDS_STATISTICAL_SEMANTIC_BINDING',N'metric_code',N'KIDS_STATISTICAL_METRIC',N'metric_code','MANY_TO_ONE',147),(N'SEMANTIC_UNIT',N'KIDS_STATISTICAL_SEMANTIC_BINDING',N'unit_code',N'KIDS_STATISTICAL_UNIT',N'unit_code','MANY_TO_ONE',148);
INSERT platform.site_contract_relation(site_contract_revision_id,relation_code,from_dataset_code,from_field_name,to_dataset_code,to_field_name,relation_kind,cardinality,required,enforcement_policy,load_priority)SELECT @site7,code,fd,ff,td,tf,'FOREIGN_KEY',card,1,'ACCESS_AND_INGEST',priority FROM @relations r WHERE NOT EXISTS(SELECT 1 FROM platform.site_contract_relation x WHERE x.site_contract_revision_id=@site7 AND x.relation_code=r.code);

/* Preserve r6 active bindings, then issue and snapshot r7. */
UPDATE platform.contract_source SET active=0 WHERE contract_id=@contract;
MERGE platform.contract_source t USING(
 SELECT @contract contract_id,N'ACCESS.'+d.access_table_name source_locator,'ACCESS_TABLE' source_kind,d.dataset_version_id,d.natural_key_expression source_key_expression,d.row_role,d.load_order,CONCAT(N'{"approvalState":"PROVISIONAL_APPROVED","canonicalAccessRevision":7,"datasetCode":"',d.dataset_code,N'","qualityPolicy":"KIDS_AGGREGATE_QUALITY_V1","confidentialityPolicy":"KIDS_PUBLIC_AGGREGATE_V1"}') mapping_spec_json
 FROM platform.site_contract_dataset d WHERE d.site_contract_revision_id=@site7
)s ON t.contract_id=s.contract_id AND t.source_locator=s.source_locator
WHEN MATCHED THEN UPDATE SET source_kind=s.source_kind,target_dataset_version_id=s.dataset_version_id,source_key_expression=s.source_key_expression,row_role=s.row_role,load_order=s.load_order,mapping_spec_json=s.mapping_spec_json,active=1
WHEN NOT MATCHED THEN INSERT(contract_id,source_locator,source_kind,target_dataset_version_id,source_key_expression,row_role,load_order,mapping_spec_json,active)VALUES(s.contract_id,s.source_locator,s.source_kind,s.dataset_version_id,s.source_key_expression,s.row_role,s.load_order,s.mapping_spec_json,1);
UPDATE platform.ingestion_contract SET contract_revision=7,format_profile='ACCESS_CANONICAL_R7_SEMANTIC',status='PROVISIONAL_APPROVED',auto_publish=0 WHERE contract_id=@contract;
IF NOT EXISTS(SELECT 1 FROM platform.ingestion_contract_revision WHERE contract_id=@contract AND revision=7)INSERT platform.ingestion_contract_revision(contract_id,revision,format_profile,lifecycle_status,compatibility_mode)VALUES(@contract,7,'ACCESS_CANONICAL_R7_SEMANTIC','PROVISIONAL_APPROVED','BACKWARD_COMPATIBLE');
DECLARE @ingestion7 BIGINT=(SELECT ingestion_contract_revision_id FROM platform.ingestion_contract_revision WHERE contract_id=@contract AND revision=7);
INSERT platform.contract_revision_source(ingestion_contract_revision_id,source_locator,source_kind,target_dataset_version_id,source_key_expression,row_role,load_order,mapping_spec_json)SELECT @ingestion7,source_locator,source_kind,target_dataset_version_id,source_key_expression,row_role,load_order,mapping_spec_json FROM platform.contract_source cs WHERE cs.contract_id=@contract AND cs.active=1 AND NOT EXISTS(SELECT 1 FROM platform.contract_revision_source x WHERE x.ingestion_contract_revision_id=@ingestion7 AND x.source_locator=cs.source_locator);
