/* Complete field contract for registry/system Access tables. Additive and idempotent. */
DECLARE @f TABLE(t NVARCHAR(160),o INT,n NVARCHAR(128),l VARCHAR(32),p VARCHAR(32),s VARCHAR(40),r BIT,e BIT);
INSERT @f VALUES
(N'GS_PACKAGE',1,N'product_code','TEXT','TEXT','ATTRIBUTE',1,0),(N'GS_PACKAGE',2,N'contract_code','TEXT','TEXT','ATTRIBUTE',1,0),(N'GS_PACKAGE',3,N'contract_revision','TEXT','TEXT','ATTRIBUTE',1,0),(N'GS_PACKAGE',4,N'package_code','CODE','TEXT','NATURAL_KEY',1,0),(N'GS_PACKAGE',5,N'package_version','TEXT','TEXT','ATTRIBUTE',1,0),(N'GS_PACKAGE',6,N'load_mode','TEXT','TEXT','ATTRIBUTE',1,0),(N'GS_PACKAGE',7,N'source_system','TEXT','TEXT','ATTRIBUTE',1,0),(N'GS_PACKAGE',8,N'artifact_profile','TEXT','TEXT','ATTRIBUTE',1,0),
(N'GS_DATASET',1,N'dataset_code','CODE','TEXT','NATURAL_KEY',1,0),(N'GS_DATASET',2,N'access_table_name','TEXT','TEXT','ATTRIBUTE',1,0),(N'GS_DATASET',3,N'data_family','CODE','TEXT','ATTRIBUTE',1,0),(N'GS_DATASET',4,N'business_grain','TEXT','MEMO','ATTRIBUTE',1,0),
(N'GS_FIELD',1,N'dataset_code','CODE','TEXT','NATURAL_KEY',1,0),(N'GS_FIELD',2,N'field_name','CODE','TEXT','NATURAL_KEY',1,0),(N'GS_FIELD',3,N'logical_type','CODE','TEXT','ATTRIBUTE',1,0),(N'GS_FIELD',4,N'semantic_role','CODE','TEXT','ATTRIBUTE',1,0),(N'GS_FIELD',5,N'required','BOOLEAN','BOOLEAN','ATTRIBUTE',1,0),
(N'GS_KEY',1,N'dataset_code','CODE','TEXT','NATURAL_KEY',1,0),(N'GS_KEY',2,N'field_name','CODE','TEXT','NATURAL_KEY',1,0),(N'GS_KEY',3,N'key_role','CODE','TEXT','ATTRIBUTE',1,0),(N'GS_KEY',4,N'key_order','INTEGER','LONG','ATTRIBUTE',1,0),
(N'GS_RELATION',1,N'relationship_code','CODE','TEXT','NATURAL_KEY',1,0),(N'GS_RELATION',2,N'from_dataset_code','CODE','TEXT','FOREIGN_KEY',1,0),(N'GS_RELATION',3,N'from_field','CODE','TEXT','FOREIGN_KEY',1,0),(N'GS_RELATION',4,N'to_dataset_code','CODE','TEXT','FOREIGN_KEY',1,0),(N'GS_RELATION',5,N'to_field','CODE','TEXT','FOREIGN_KEY',1,0),(N'GS_RELATION',6,N'cardinality','CODE','TEXT','ATTRIBUTE',1,0),(N'GS_RELATION',7,N'required','BOOLEAN','BOOLEAN','ATTRIBUTE',1,0),
(N'GS_PROJECTION',1,N'projection_code','CODE','TEXT','NATURAL_KEY',1,0),(N'GS_PROJECTION',2,N'dataset_code','CODE','TEXT','FOREIGN_KEY',1,0),(N'GS_PROJECTION',3,N'projection_family','CODE','TEXT','ATTRIBUTE',1,0),(N'GS_PROJECTION',4,N'mapping_json','TEXT','MEMO','ATTRIBUTE',1,0),(N'GS_PROJECTION',5,N'approval_state','CODE','TEXT','ATTRIBUTE',1,0),
(N'CL_SCHEME',1,N'scheme_code','CODE','TEXT','NATURAL_KEY',1,0),(N'CL_SCHEME',2,N'authority_mode','CODE','TEXT','ATTRIBUTE',1,0),(N'CL_SCHEME',3,N'title','TEXT','MEMO','CONTENT',1,1),(N'CL_SCHEME',4,N'standard_reference','TEXT','TEXT','ATTRIBUTE',0,1),
(N'CL_VERSION',1,N'version_ref','CODE','TEXT','NATURAL_KEY',1,0),(N'CL_VERSION',2,N'scheme_code','CODE','TEXT','FOREIGN_KEY',1,0),(N'CL_VERSION',3,N'version_code','CODE','TEXT','ATTRIBUTE',1,0),(N'CL_VERSION',4,N'lifecycle_state','CODE','TEXT','ATTRIBUTE',1,0),(N'CL_VERSION',5,N'valid_from','DATE','SHORT_DATE_TIME','ATTRIBUTE',1,0),(N'CL_VERSION',6,N'valid_to','DATE','SHORT_DATE_TIME','ATTRIBUTE',0,1),
(N'CL_ITEM',1,N'item_ref','CODE','TEXT','NATURAL_KEY',1,0),(N'CL_ITEM',2,N'version_ref','CODE','TEXT','FOREIGN_KEY',1,0),(N'CL_ITEM',3,N'item_code','CODE','TEXT','ATTRIBUTE',1,0),(N'CL_ITEM',4,N'label_ka','TEXT','MEMO','LOCALIZED_TEXT',0,1),(N'CL_ITEM',5,N'label_en','TEXT','MEMO','LOCALIZED_TEXT',0,1),(N'CL_ITEM',6,N'lifecycle_state','CODE','TEXT','ATTRIBUTE',1,0),(N'CL_ITEM',7,N'sort_order','INTEGER','LONG','ATTRIBUTE',0,1),
(N'CL_ALIAS',1,N'alias_ref','CODE','TEXT','NATURAL_KEY',1,0),(N'CL_ALIAS',2,N'item_ref','CODE','TEXT','FOREIGN_KEY',1,0),(N'CL_ALIAS',3,N'source_system','CODE','TEXT','ATTRIBUTE',1,0),(N'CL_ALIAS',4,N'source_code_raw','TEXT','MEMO','ATTRIBUTE',1,1),(N'CL_ALIAS',5,N'lookup_code_normalized','TEXT','MEMO','ATTRIBUTE',1,1),(N'CL_ALIAS',6,N'normalization_rule','TEXT','TEXT','ATTRIBUTE',1,1),(N'CL_ALIAS',7,N'lifecycle_state','CODE','TEXT','ATTRIBUTE',1,0),
(N'CL_HIERARCHY',1,N'version_ref','CODE','TEXT','FOREIGN_KEY',1,0),(N'CL_HIERARCHY',2,N'parent_item_ref','CODE','TEXT','FOREIGN_KEY',0,1),(N'CL_HIERARCHY',3,N'child_item_ref','CODE','TEXT','FOREIGN_KEY',1,0),(N'CL_HIERARCHY',4,N'ordinal','INTEGER','LONG','ATTRIBUTE',1,0),
(N'STAT_UNIT',1,N'unit_code','CODE','TEXT','NATURAL_KEY',1,0),(N'STAT_UNIT',2,N'quantity_kind','CODE','TEXT','ATTRIBUTE',1,0),(N'STAT_UNIT',3,N'scale_factor','DECIMAL','DOUBLE','ATTRIBUTE',1,0),(N'STAT_UNIT',4,N'denominator_text','TEXT','MEMO','ATTRIBUTE',0,1),(N'STAT_UNIT',5,N'title','TEXT','MEMO','CONTENT',1,1),
(N'STAT_METRIC',1,N'metric_code','CODE','TEXT','NATURAL_KEY',1,0),(N'STAT_METRIC',2,N'source_resource_id','CODE','TEXT','FOREIGN_KEY',1,0),(N'STAT_METRIC',3,N'title_ka','TEXT','MEMO','LOCALIZED_TEXT',0,1),(N'STAT_METRIC',4,N'title_en','TEXT','MEMO','LOCALIZED_TEXT',0,1),(N'STAT_METRIC',5,N'measure_component_code','CODE','TEXT','ATTRIBUTE',1,0),(N'STAT_METRIC',6,N'unit_code','CODE','TEXT','FOREIGN_KEY',1,0),(N'STAT_METRIC',7,N'aggregation','CODE','TEXT','ATTRIBUTE',1,0),(N'STAT_METRIC',8,N'lifecycle_state','CODE','TEXT','ATTRIBUTE',1,0),(N'STAT_METRIC',9,N'inference_confidence','DECIMAL','DOUBLE','ATTRIBUTE',1,0),(N'STAT_METRIC',10,N'inference_rationale','TEXT','MEMO','ATTRIBUTE',1,1),
(N'RAW_DOCUMENT',1,N'source_row_key','CODE','TEXT','NATURAL_KEY',1,0),(N'RAW_DOCUMENT',2,N'source_table','TEXT','TEXT','ATTRIBUTE',1,0),(N'RAW_DOCUMENT',3,N'source_primary_key','TEXT','TEXT','ATTRIBUTE',1,0),(N'RAW_DOCUMENT',4,N'extract_sequence','INTEGER','LONG','ATTRIBUTE',1,0);
INSERT platform.contract_field_definition(table_definition_id,field_name,ordinal,logical_type,physical_type,semantic_role,required,nullable,ui_control_type,ui_visible,ui_editable,ui_filterable,ui_sortable,ui_groupable,lifecycle_status)
SELECT td.table_definition_id,f.n,f.o,f.l,f.p,f.s,f.r,CASE WHEN f.r=1 THEN 0 ELSE 1 END,CASE WHEN f.l='INTEGER' THEN 'NUMBER' WHEN f.l='DECIMAL' THEN 'NUMBER' WHEN f.l='DATE' THEN 'DATE' ELSE 'TEXT' END,1,CASE WHEN f.e=1 THEN 1 ELSE 0 END,1,1,CASE WHEN f.s='ATTRIBUTE' THEN 1 ELSE 0 END,'APPROVED'
FROM @f f JOIN platform.contract_table_definition td ON td.logical_table_code=f.t AND td.revision=1
WHERE NOT EXISTS(SELECT 1 FROM platform.contract_field_definition x WHERE x.table_definition_id=td.table_definition_id AND x.field_name=f.n);
