/* Revision 9: complete the physical structure index and raw artifact envelope. */
DECLARE @gs BIGINT=(SELECT structure_id FROM platform.contract_structure WHERE structure_code=N'GS_STRUCTURE_INDEX' AND revision=1);
IF @gs IS NULL BEGIN
  DECLARE @ns BIGINT=(SELECT namespace_id FROM platform.contract_namespace WHERE namespace_code=N'GS');
  INSERT platform.contract_structure(namespace_id,structure_code,structure_kind,data_class,grain,authority_mode,lifecycle_policy,allowed_content,forbidden_content,lineage_policy,ui_capabilities_json,lifecycle_status,revision)
  VALUES(@ns,N'GS_STRUCTURE_INDEX','CONTRACT','METADATA',N'one registered logical structure','AUTHORITATIVE','IMMUTABLE',N'one row per declared namespace structure',N'undeclared or business rows',N'contract registry identity',N'{"list":true,"detail":true,"create":false,"edit":false,"approve":true,"import":false,"export":true}','APPROVED',1);
  SET @gs=SCOPE_IDENTITY();
  INSERT platform.contract_table_definition(structure_id,logical_table_code,physical_table_name,access_table_name,table_role,storage_plane,primary_key_expression,load_order,required,lifecycle_status,revision)
  VALUES(@gs,N'GS_STRUCTURE_INDEX',N'__gs_structure_index',N'__gs_structure_index','METADATA','ACCESS',N'structure_code',7,1,'APPROVED',1);
END;
DECLARE @td BIGINT=(SELECT table_definition_id FROM platform.contract_table_definition WHERE logical_table_code=N'GS_STRUCTURE_INDEX' AND revision=1);
INSERT platform.contract_field_definition(table_definition_id,field_name,ordinal,logical_type,physical_type,semantic_role,required,nullable,ui_control_type,ui_visible,ui_editable,ui_filterable,ui_sortable,ui_groupable,lifecycle_status)
SELECT @td,v.field_name,v.ordinal,v.logical_type,v.physical_type,v.semantic_role,1,0,v.ui_control_type,1,0,1,1,0,'APPROVED' FROM (VALUES
(N'structure_code',1,'CODE','TEXT','NATURAL_KEY','TEXT'),(N'namespace_code',2,'CODE','TEXT','ATTRIBUTE','TEXT'),(N'structure_kind',3,'CODE','TEXT','ATTRIBUTE','SELECT'),(N'data_class',4,'CODE','TEXT','ATTRIBUTE','SELECT'),(N'grain',5,'TEXT','MEMO','ATTRIBUTE','TEXT'),(N'authority_mode',6,'CODE','TEXT','ATTRIBUTE','SELECT'),(N'lifecycle_policy',7,'CODE','TEXT','ATTRIBUTE','SELECT'),(N'lifecycle_status',8,'CODE','TEXT','ATTRIBUTE','SELECT'),(N'revision',9,'INTEGER','LONG','ATTRIBUTE','NUMBER'),(N'checksum',10,'CODE','TEXT','ATTRIBUTE','TEXT'))v(field_name,ordinal,logical_type,physical_type,semantic_role,ui_control_type)
WHERE NOT EXISTS(SELECT 1 FROM platform.contract_field_definition f WHERE f.table_definition_id=@td AND f.field_name=v.field_name);
DECLARE @raw BIGINT=(SELECT table_definition_id FROM platform.contract_table_definition WHERE logical_table_code=N'KIDS_RAW_DOCUMENT' AND revision=1);
INSERT platform.contract_field_definition(table_definition_id,field_name,ordinal,logical_type,physical_type,semantic_role,required,nullable,ui_control_type,ui_visible,ui_editable,ui_filterable,ui_sortable,ui_groupable,lifecycle_status)
SELECT @raw,v.field_name,v.ordinal,v.logical_type,v.physical_type,v.semantic_role,v.required,CASE WHEN v.required=1 THEN 0 ELSE 1 END,v.ui_control_type,1,0,1,1,0,'APPROVED' FROM (VALUES
(N'source_system',5,'CODE','TEXT','PROVENANCE',1,'TEXT'),(N'source_feed',6,'CODE','TEXT','PROVENANCE',0,'TEXT'),(N'document_identity',7,'CODE','TEXT','NATURAL_KEY',1,'TEXT'),(N'original_filename',8,'TEXT','MEMO','ATTRIBUTE',0,'TEXT'),(N'mime_type',9,'CODE','TEXT','ATTRIBUTE',0,'TEXT'),(N'byte_size',10,'INTEGER','LONG','ATTRIBUTE',0,'NUMBER'),(N'checksum',11,'CODE','TEXT','CHECKSUM',1,'TEXT'),(N'received_at',12,'DATE','SHORT_DATE_TIME','TIMESTAMP',1,'DATE'),(N'source_uri',13,'URI','MEMO','LOCATOR',0,'TEXT'),(N'ingestion_batch',14,'CODE','TEXT','PROVENANCE',1,'TEXT'),(N'provenance',15,'TEXT','MEMO','PROVENANCE',1,'TEXT'),(N'retention_policy',16,'CODE','TEXT','RETENTION',1,'TEXT'),(N'confidentiality_class',17,'CODE','TEXT','CONFIDENTIALITY',1,'TEXT'),(N'payload_reference',18,'URI','MEMO','LOCATOR',1,'TEXT'),(N'encryption_reference',19,'CODE','TEXT','SECURITY',0,'TEXT'),(N'parser_status',20,'CODE','TEXT','STATUS',1,'SELECT'),(N'validation_status',21,'CODE','TEXT','STATUS',1,'SELECT'),(N'supersedes_source_row_key',22,'CODE','TEXT','RELATION',0,'TEXT'))v(field_name,ordinal,logical_type,physical_type,semantic_role,required,ui_control_type)
WHERE @raw IS NOT NULL AND NOT EXISTS(SELECT 1 FROM platform.contract_field_definition f WHERE f.table_definition_id=@raw AND f.field_name=v.field_name);
INSERT platform.contract_index_definition(table_definition_id,index_code,index_kind,field_list,is_unique,required,lifecycle_status)
SELECT td.table_definition_id,CONCAT(td.logical_table_code,N'__PK'),'PRIMARY',td.primary_key_expression,1,1,'APPROVED' FROM platform.contract_table_definition td WHERE td.logical_table_code=N'GS_STRUCTURE_INDEX' AND td.revision=1 AND NOT EXISTS(SELECT 1 FROM platform.contract_index_definition i WHERE i.table_definition_id=td.table_definition_id AND i.index_code=CONCAT(td.logical_table_code,N'__PK'));
INSERT platform.contract_index_definition(table_definition_id,index_code,index_kind,field_list,is_unique,required,lifecycle_status)
SELECT @raw,N'KIDS_RAW_DOCUMENT__IX__CHECKSUM','SECONDARY',N'checksum',0,0,'APPROVED' WHERE @raw IS NOT NULL AND NOT EXISTS(SELECT 1 FROM platform.contract_index_definition i WHERE i.table_definition_id=@raw AND i.index_code=N'KIDS_RAW_DOCUMENT__IX__CHECKSUM');
