/* KIDS final page-aware contract. r7 remains immutable; r8 is additive. */
DECLARE @product BIGINT=(SELECT product_id FROM platform.data_product WHERE product_code=N'KIDS_PORTAL');
DECLARE @parent BIGINT=(SELECT site_contract_revision_id FROM platform.site_contract_revision WHERE contract_code=N'KIDS_PORTAL_V1' AND revision=7);
DECLARE @doc NVARCHAR(MAX)=N'{"contract":"KIDS_PORTAL_V1","revision":8,"parent":7,"compatibility":"BACKWARD_COMPATIBLE","accessProfile":"ACCESS_CANONICAL_R8_PAGE_MANIFEST","datasets":15,"fields":104,"relations":21,"semanticBindings":43,"pages":6,"pageIdentity":"CONTROL_PLANE_NODE_ID","aggregation":"NONE","qualityPolicy":"KIDS_AGGREGATE_QUALITY_V1","confidentialityPolicy":"KIDS_PUBLIC_AGGREGATE_V1"}';
IF NOT EXISTS(SELECT 1 FROM platform.site_contract_revision WHERE contract_code=N'KIDS_PORTAL_V1' AND revision=8)
INSERT platform.site_contract_revision(product_id,contract_code,revision,parent_revision_id,schema_standard,compatibility_mode,status,contract_checksum,contract_document_json) VALUES(@product,N'KIDS_PORTAL_V1',8,@parent,N'ISO/IEC 11179 + SDMX information model',N'BACKWARD_COMPATIBLE','APPROVED',CONVERT(VARCHAR(64),HASHBYTES('SHA2_256',CONVERT(VARBINARY(MAX),@doc)),2),@doc);
DECLARE @r BIGINT=(SELECT site_contract_revision_id FROM platform.site_contract_revision WHERE contract_code=N'KIDS_PORTAL_V1' AND revision=8);
INSERT platform.site_contract_dataset(site_contract_revision_id,dataset_version_id,dataset_code,access_table_name,data_family,business_grain,natural_key_expression,row_role,load_order,required) SELECT @r,dataset_version_id,dataset_code,access_table_name,data_family,business_grain,natural_key_expression,row_role,load_order,required FROM platform.site_contract_dataset d WHERE d.site_contract_revision_id=@parent AND NOT EXISTS(SELECT 1 FROM platform.site_contract_dataset x WHERE x.site_contract_revision_id=@r AND x.dataset_code=d.dataset_code);
INSERT platform.site_contract_field(contract_dataset_id,field_name,logical_type,semantic_role,ordinal,required,key_role,classifier_scheme_code,source_expression,normalization_rule) SELECT t.contract_dataset_id,f.field_name,f.logical_type,f.semantic_role,f.ordinal,f.required,f.key_role,f.classifier_scheme_code,f.source_expression,f.normalization_rule FROM platform.site_contract_field f JOIN platform.site_contract_dataset old ON old.contract_dataset_id=f.contract_dataset_id AND old.site_contract_revision_id=@parent JOIN platform.site_contract_dataset t ON t.site_contract_revision_id=@r AND t.dataset_code=old.dataset_code WHERE NOT EXISTS(SELECT 1 FROM platform.site_contract_field x WHERE x.contract_dataset_id=t.contract_dataset_id AND x.field_name=f.field_name);
INSERT platform.site_contract_relation(site_contract_revision_id,relation_code,from_dataset_code,from_field_name,to_dataset_code,to_field_name,relation_kind,cardinality,required,enforcement_policy,load_priority) SELECT @r,relation_code,from_dataset_code,from_field_name,to_dataset_code,to_field_name,relation_kind,cardinality,required,enforcement_policy,load_priority FROM platform.site_contract_relation x WHERE x.site_contract_revision_id=@parent AND NOT EXISTS(SELECT 1 FROM platform.site_contract_relation y WHERE y.site_contract_revision_id=@r AND y.relation_code=x.relation_code);
INSERT platform.site_contract_classifier(site_contract_revision_id,scheme_code,version_policy,authority_mode,unknown_value_policy,publication_policy) SELECT @r,scheme_code,version_policy,authority_mode,unknown_value_policy,publication_policy FROM platform.site_contract_classifier x WHERE x.site_contract_revision_id=@parent AND NOT EXISTS(SELECT 1 FROM platform.site_contract_classifier y WHERE y.site_contract_revision_id=@r AND y.scheme_code=x.scheme_code);
INSERT platform.site_contract_gate(site_contract_revision_id,gate_code,gate_type,severity,blocking,rule_json) SELECT @r,gate_code,gate_type,severity,blocking,rule_json FROM platform.site_contract_gate x WHERE x.site_contract_revision_id=@parent AND NOT EXISTS(SELECT 1 FROM platform.site_contract_gate y WHERE y.site_contract_revision_id=@r AND y.gate_code=x.gate_code);
DECLARE @map TABLE(old_id BIGINT,new_id BIGINT);
INSERT platform.site_contract_node(site_contract_revision_id,node_code,node_kind,path_segment,sort_order,required,title_ka,title_en) OUTPUT NULL,INSERTED.node_id INTO @map(old_id,new_id) SELECT @r,node_code,node_kind,path_segment,sort_order,required,title_ka,title_en FROM platform.site_contract_node WHERE site_contract_revision_id=@parent AND parent_node_id IS NULL AND NOT EXISTS(SELECT 1 FROM platform.site_contract_node z WHERE z.site_contract_revision_id=@r AND z.node_code=platform.site_contract_node.node_code);
UPDATE m SET old_id=o.node_id FROM @map m JOIN platform.site_contract_node n ON n.node_id=m.new_id JOIN platform.site_contract_node o ON o.site_contract_revision_id=@parent AND o.node_code=n.node_code;
INSERT @map(old_id,new_id) SELECT o.node_id,n.node_id FROM platform.site_contract_node o JOIN platform.site_contract_node n ON n.site_contract_revision_id=@r AND n.node_code=o.node_code WHERE o.site_contract_revision_id=@parent AND NOT EXISTS(SELECT 1 FROM @map m WHERE m.old_id=o.node_id);
INSERT platform.site_contract_node(site_contract_revision_id,node_code,parent_node_id,node_kind,dataset_code,path_segment,sort_order,required,title_ka,title_en) SELECT @r,n.node_code,m.new_id,n.node_kind,n.dataset_code,n.path_segment,n.sort_order,n.required,n.title_ka,n.title_en FROM platform.site_contract_node n JOIN @map m ON m.old_id=n.parent_node_id WHERE n.site_contract_revision_id=@parent AND NOT EXISTS(SELECT 1 FROM platform.site_contract_node z WHERE z.site_contract_revision_id=@r AND z.node_code=n.node_code);
INSERT platform.contract_page_binding(site_contract_revision_id,page_code,node_id,dataset_code,response_projection_code,access_page_code) SELECT @r,n.node_code,n.node_id,n.dataset_code,CASE n.node_code WHEN N'KIDS_GOALS' THEN N'KIDS_GOAL_ENTITY' WHEN N'KIDS_RESOURCES' THEN N'KIDS_RESOURCE_ENTITY' WHEN N'KIDS_GLOSSARY' THEN N'KIDS_GLOSSARY_ENTRY_ENTITY' WHEN N'KIDS_STATISTICS' THEN N'KIDS_STATS_INPUT' END,n.node_code FROM platform.site_contract_node n WHERE n.site_contract_revision_id=@r AND NOT EXISTS(SELECT 1 FROM platform.contract_page_binding b WHERE b.site_contract_revision_id=@r AND b.page_code=n.node_code);
