import com.healthmarketscience.jackcess.*;
import java.io.File;
import java.util.Set;

/** Creates the empty, immutable-shape KIDS_PORTAL_V1 revision-2 Access v3 template. */
public final class KidsPortalAccessV3TemplateGenerator {
  public static void main(String[] a)throws Exception{
    File out=new File(a.length==0?"samples/kids-portal-v1-access-v3-template.accdb":a[0]); if(out.exists())throw new IllegalStateException("Refusing overwrite: "+out); if(out.getParentFile()!=null)out.getParentFile().mkdirs();
    try(Database d=DatabaseBuilder.create(Database.FileFormat.V2010,out)){ meta(d); source(d,"goals_titles","ID","category","title_geo","title_eng"); source(d,"goals","ID","category","title_geo","title_eng","path_geo","path_eng"); source(d,"files","ID","category","sub_category","title_geo","title_eng","path_geo","path_eng","chartdata"); source(d,"glossary","ID","lang","text"); statisticalBindings(d); if(a.length>1)copySource(d,new File(a[1])); }
  }
  /** Optional second argument is a read-only legacy export. It copies source rows byte-for-byte in meaning, never interprets chartdata. */
  static final Set<Long> VERIFIED_JSON_CARRIERS=Set.of(162L,163L,164L,165L,166L,167L,168L,169L,170L,171L,172L,173L,174L,175L,176L,177L,178L,179L,180L,181L,183L,297L,299L,301L,303L,305L,306L,308L,310L,385L,386L,387L);
  static void copySource(Database target,File input)throws Exception{if(!input.isFile())throw new IllegalArgumentException("Legacy Access export not found: "+input);try(Database source=DatabaseBuilder.open(input)){for(String name:new String[]{"goals_titles","goals","files","glossary"}){Table from=source.getTable(name),to=target.getTable(name);if(from==null)throw new IllegalArgumentException("Legacy export misses required table: "+name);for(Row row:from){Object[] values=new Object[to.getColumnCount()];for(int i=0;i<to.getColumnCount();i++)values[i]=row.get(to.getColumns().get(i).getName());to.addRow(values);}}}Table bindings=target.getTable("__gs_statistical_binding");for(Row row:target.getTable("files")){long id=((Number)row.get("ID")).longValue();if(VERIFIED_JSON_CARRIERS.contains(id))bindings.addRow("KIDS_FILE_RESOURCE",String.valueOf(id),"KIDS_STATS","KIDS_FILES_STATISTICS","DRAFT","VERIFIED_JSON_ARRAY_OR_ESCAPED_TEXT");}}
  static void meta(Database d)throws Exception{
    txt(d,"__gs_package","product_code","contract_code","contract_revision","package_code","package_version").addRow("KIDS_PORTAL","KIDS_PORTAL_V1","2","kids-portal-v1","3.0.0");
    Table ds=txt(d,"__gs_dataset","dataset_code","access_table_name","data_family","business_grain"); ds.addRow("KIDS_GOAL_CATEGORY_REFERENCE","goals_titles","REFERENCE","one category");ds.addRow("KIDS_GOAL","goals","ENTITY","one goal");ds.addRow("KIDS_FILE_RESOURCE","files","ENTITY","one file resource");ds.addRow("KIDS_GLOSSARY_ENTRY","glossary","ENTITY","one glossary entry");
    Table f=txt(d,"__gs_field","dataset_code","field_name","logical_type","semantic_role","required"); add(f,"KIDS_GOAL_CATEGORY_REFERENCE",new String[]{"ID","category","title_geo","title_eng"});add(f,"KIDS_GOAL",new String[]{"ID","category","title_geo","title_eng","path_geo","path_eng"});add(f,"KIDS_FILE_RESOURCE",new String[]{"ID","category","sub_category","title_geo","title_eng","path_geo","path_eng","chartdata"});add(f,"KIDS_GLOSSARY_ENTRY",new String[]{"ID","lang","text"});
    Table k=txt(d,"__gs_key","dataset_code","field_name","key_role","key_order");for(String x:new String[]{"KIDS_GOAL_CATEGORY_REFERENCE","KIDS_GOAL","KIDS_FILE_RESOURCE","KIDS_GLOSSARY_ENTRY"})k.addRow(x,"ID","NATURAL","1");
    Table r=txt(d,"__gs_relation","relationship_code","from_dataset_code","from_field","to_dataset_code","to_field","cardinality","required");r.addRow("GOAL_CATEGORY","KIDS_GOAL","category","KIDS_GOAL_CATEGORY_REFERENCE","ID","MANY_TO_ONE","true");r.addRow("FILE_CATEGORY","KIDS_FILE_RESOURCE","category","KIDS_GOAL_CATEGORY_REFERENCE","ID","MANY_TO_ONE","true");
    Table p=projections(d);p.addRow("KIDS_CATEGORY","KIDS_GOAL_CATEGORY_REFERENCE","REFERENCE","{\"approvalState\":\"DRAFT\"}","DRAFT");p.addRow("KIDS_GOALS","KIDS_GOAL","ENTITY","{\"approvalState\":\"DRAFT\",\"key\":\"ID\"}","DRAFT");p.addRow("KIDS_FILES","KIDS_FILE_RESOURCE","ENTITY","{\"approvalState\":\"DRAFT\",\"key\":\"ID\"}","DRAFT");p.addRow("KIDS_STATS","KIDS_FILE_RESOURCE","STATISTICAL_WIDE_JSON","{\"projection_family\":\"STATISTICAL_WIDE_JSON\",\"dataflow_code\":\"KIDS_FILES_STATISTICS\",\"dsd_revision\":1,\"array_path\":\"chartdata\",\"period_field\":\"year\",\"pivot_dimension\":\"AGE_GROUP\",\"raw_key_normalization\":\"TRIM_FOR_ALIAS_LOOKUP_ONLY\",\"approval_state\":\"DRAFT\"}","DRAFT");p.addRow("KIDS_GLOSSARY","KIDS_GLOSSARY_ENTRY","ENTITY","{\"approvalState\":\"DRAFT\",\"key\":\"ID\"}","DRAFT");
  }
  static void add(Table t,String d,String[] fs)throws Exception{for(String f:fs)t.addRow(d,f,f.equals("ID")?"INTEGER":f.contains("path")?"URI":f.equals("chartdata")?"JSON":"TEXT",f.equals("ID")?"NATURAL_KEY":f.equals("category")?"FOREIGN_KEY":f.equals("chartdata")?"RAW_PAYLOAD":"ATTRIBUTE","true");}
  static Table projections(Database d)throws Exception{TableBuilder b=new TableBuilder("__gs_projection");b.addColumn(new ColumnBuilder("projection_code",DataType.TEXT));b.addColumn(new ColumnBuilder("dataset_code",DataType.TEXT));b.addColumn(new ColumnBuilder("projection_family",DataType.TEXT));b.addColumn(new ColumnBuilder("mapping_json",DataType.MEMO));b.addColumn(new ColumnBuilder("approval_state",DataType.TEXT));return b.toTable(d);}
  static void statisticalBindings(Database d)throws Exception{TableBuilder b=new TableBuilder("__gs_statistical_binding");for(String c:new String[]{"source_dataset_code","source_external_key","projection_code","dataflow_code","binding_state","evidence_kind"})b.addColumn(new ColumnBuilder(c,DataType.TEXT));b.toTable(d);}
  static void source(Database d,String n,String...fs)throws Exception{TableBuilder b=new TableBuilder(n);for(String f:fs)b.addColumn(new ColumnBuilder(f,f.equals("ID")||f.equals("category")?DataType.LONG:DataType.MEMO));b.toTable(d);}static Table txt(Database d,String n,String...fs)throws Exception{TableBuilder b=new TableBuilder(n);for(String f:fs)b.addColumn(new ColumnBuilder(f,DataType.TEXT));return b.toTable(d);}
}
