import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.healthmarketscience.jackcess.*;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;

/**
 * Generates the canonical, data-bearing KIDS Access package from the read-only legacy KIDS export.
 * It never copies legacy tables as the target contract and never assigns official statistical meaning
 * to chart JSON. Usage: java ... KidsPortalCanonicalAccessPackageGenerator output.accdb source.accdb
 */
public final class KidsPortalCanonicalAccessPackageGenerator {
  private static final String SCHEME_GOAL="KIDS_GOAL_CATEGORY", SCHEME_LANGUAGE="LANGUAGE", SCHEME_SUB="KIDS_RESOURCE_SUBCATEGORY", SCHEME_AGE="AGE_GROUP";
  private static final String VERSION="KIDS_PORTAL_V1_SOURCE_2026_09_R8";
  private static final ObjectMapper JSON=new ObjectMapper();
  private static File SOURCE_ARTIFACT;
  private static String SOURCE_CHECKSUM;
  private record Semantic(String metric,String unit,double confidence,String rationale){}
  private static final Map<String,Semantic> SEMANTICS=Map.ofEntries(
    sem("162","ABORTIONS_COUNT","COUNT_EVENT",.99,"Title explicitly states number of abortions"),sem("163","MALIGNANT_NEOPLASM_NEW_CASES","COUNT_CASE",.99,"Title explicitly states new cases"),sem("164","SEXUALLY_TRANSMITTED_DISEASE_NEW_CASES","COUNT_CASE",.99,"Title explicitly states new cases"),sem("165","DIABETES_MELLITUS_NEW_CASES","COUNT_CASE",.99,"Title explicitly states new cases"),
    sem("166","RESPIRATORY_TUBERCULOSIS_CASES","COUNT_CASE",.98,"Title states number of disease cases"),sem("167","TUBERCULOUS_MENINGITIS_CASES","COUNT_CASE",.98,"Title states number of disease cases"),sem("168","MUSCULOSKELETAL_TUBERCULOSIS_CASES","COUNT_CASE",.98,"Title states number of disease cases"),sem("169","INFECTIOUS_PARASITIC_DISEASE_NEW_CASES","COUNT_CASE",.99,"Title explicitly states new cases"),sem("170","BLOOD_DISEASE_NEW_CASES","COUNT_CASE",.99,"Title explicitly states new cases"),sem("171","ENDOCRINE_METABOLIC_DISEASE_NEW_CASES","COUNT_CASE",.98,"Title explicitly states new cases"),sem("172","MENTAL_BEHAVIOURAL_DISORDER_NEW_CASES","COUNT_CASE",.99,"Title explicitly states new cases"),sem("173","NERVOUS_SYSTEM_DISEASE_NEW_CASES","COUNT_CASE",.99,"Title explicitly states new cases"),sem("174","EYE_ADNEXA_DISEASE_NEW_CASES","COUNT_CASE",.99,"Title explicitly states new cases"),sem("175","EAR_MASTOID_DISEASE_NEW_CASES","COUNT_CASE",.99,"Title explicitly states new cases"),sem("176","CIRCULATORY_DISEASE_NEW_CASES","COUNT_CASE",.99,"Title explicitly states new cases"),sem("177","RESPIRATORY_DISEASE_NEW_CASES","COUNT_CASE",.99,"Title explicitly states new cases"),sem("178","DIGESTIVE_DISEASE_NEW_CASES","COUNT_CASE",.99,"Title explicitly states new cases"),sem("179","SKIN_SUBCUTANEOUS_DISEASE_NEW_CASES","COUNT_CASE",.99,"Title explicitly states new cases"),sem("180","MUSCULOSKELETAL_DISEASE_NEW_CASES","COUNT_CASE",.99,"Title explicitly states new cases"),sem("181","UROGENITAL_DISEASE_NEW_CASES","COUNT_CASE",.99,"Title explicitly states new cases"),sem("183","CONGENITAL_MALFORMATION_NEW_CASES","COUNT_CASE",.99,"Title explicitly states new cases"),
    sem("297","DISABILITY_SOCIAL_PACKAGE_RECIPIENTS","PERSON",.98,"Title states number of persons"),sem("299","SURVIVOR_SOCIAL_PACKAGE_RECIPIENTS","PERSON",.95,"Title identifies recipients by age"),sem("301","SUBSISTENCE_ALLOWANCE_BENEFICIARIES","PERSON",.99,"Title states number of beneficiaries"),sem("303","PLANNED_OUTPATIENT_REGISTERED_PERSONS","PERSON",.99,"Title states number of registered persons"),sem("305","CHRONIC_MEDICINE_PROGRAM_BENEFICIARIES","PERSON",.99,"Title states number of beneficiaries"),sem("306","ADOPTED_CHILDREN","PERSON",.99,"Title counts adopted children"),sem("308","CHILDREN_GRANTED_ADOPTION_STATUS","PERSON",.96,"Title and integer values indicate children granted status"),sem("310","INTERNALLY_DISPLACED_PERSONS","PERSON",.99,"Title states number of persons"),
    sem("373","LABOUR_FORCE_POPULATION","THOUSAND_PERSONS",.85,"Magnitude and source workbook identify labour-force population in thousands"),sem("385","RESIDENT_VISITORS_MONTHLY_AVERAGE","THOUSAND_PERSONS",.99,"Title explicitly states thousand visitors"),sem("386","DOMESTIC_VISITS_MONTHLY_AVERAGE","THOUSAND_VISITS",.99,"Title explicitly states thousand visits"),sem("387","AVERAGE_NIGHTS_PER_VISIT","AVERAGE_NIGHTS",.99,"Title explicitly states average number of nights"),
    sem("404","MATERNAL_MORTALITY_RATIO","PER_100000_LIVE_BIRTHS",.99,"Title explicitly gives denominator"),sem("407","HIV_INCIDENCE_RATE","PER_1000_UNINFECTED_POPULATION",.99,"Title explicitly gives denominator"),sem("409","ANAEMIA_PREVALENCE","PERCENT",.95,"Prevalence values and SDG convention imply percent"),sem("417","SUICIDES_COUNT","COUNT_EVENT",.99,"Title and integral values identify event counts"),sem("418","SUICIDE_MORTALITY_RATE","PER_100000_POPULATION",.97,"SDG 3.4.2 is defined per 100,000 population"),
    sem("438","DAILY_INTERNET_USE_SHARE","PERCENT",.99,"Title states population share"),sem("439","RECENT_COMPUTER_USE_SHARE","PERCENT",.99,"Title states population share"),sem("440","MOBILE_PHONE_USE_SHARE","PERCENT",.99,"Title states population share"),sem("451","LITERACY_RATE","PERCENT",.99,"Title states rate and values are percentages"),sem("452","EARLY_EDUCATION_LEAVERS_RATE","PERCENT",.97,"Indicator convention and 0-100 values imply percent")
  );
  private static Map.Entry<String,Semantic> sem(String id,String metric,String unit,double confidence,String rationale){return Map.entry(id,new Semantic("KIDS_"+metric,unit,confidence,rationale));}
  public static void main(String[] args) throws Exception {
    File out=new File(args.length>0?args[0]:"samples/kids-portal-v1-canonical-r7.accdb");
    File source=new File(args.length>1?args[1]:"samples/kids-children-portal-full-data.accdb");
    if(out.exists()) throw new IllegalStateException("Refusing to overwrite: "+out.getAbsolutePath());
    if(!source.isFile()) throw new IllegalArgumentException("KIDS source export not found: "+source.getAbsolutePath());
    if(out.getParentFile()!=null) out.getParentFile().mkdirs();
    SOURCE_ARTIFACT=source; SOURCE_CHECKSUM=shaFile(source);
    try(Database target=DatabaseBuilder.create(Database.FileFormat.V2010,out); Database legacy=new DatabaseBuilder(source).setReadOnly(true).open()) {
      create(target); load(target,legacy); populateMetadata(target); addPhysicalRelationships(target); verify(target,legacy);
    }
    System.out.println("Created canonical KIDS package: "+out.getAbsolutePath());
  }
  private static void create(Database d)throws Exception {
    text(d,"__gs_package","product_code","contract_code","contract_revision","package_code","package_version","load_mode","source_system","artifact_profile")
      .addRow("KIDS_PORTAL","KIDS_PORTAL_V1","8","kids-portal-canonical","8.0.0","SNAPSHOT","KIDS_LEGACY_ACCESS","ACCESS_CANONICAL_R8_PAGE_MANIFEST");
    text(d,"__gs_dataset","dataset_code","access_table_name","data_family","business_grain");
    text(d,"__gs_field","dataset_code","field_name","logical_type","semantic_role","required");
    text(d,"__gs_key","dataset_code","field_name","key_role","key_order");
    text(d,"__gs_relation","relationship_code","from_dataset_code","from_field","to_dataset_code","to_field","cardinality","required");
    memo(d,"__gs_projection","projection_code","dataset_code","projection_family","mapping_json","approval_state");
    memo(d,"__gs_metadata_schema","schema_code","namespace_code","schema_revision","schema_json","approval_state");
    memo(d,"__gs_metadata","subject_type","subject_code","subject_revision","namespace_code","property_code","language_tag","value_type","value_text","value_json","ordinal","lifecycle_status","source_reference");
    text(d,"__gs_page","page_code","node_code","contract_code","contract_revision","parent_page_code","node_kind","dataset_code","path_segment","response_projection_code","sort_order","required","approval_state");
    table(d,"__cl_scheme", cols("scheme_code",DataType.TEXT,"authority_mode",DataType.TEXT,"title",DataType.MEMO,"standard_reference",DataType.TEXT));
    table(d,"__cl_version", cols("version_ref",DataType.TEXT,"scheme_code",DataType.TEXT,"version_code",DataType.TEXT,"lifecycle_state",DataType.TEXT,"valid_from",DataType.TEXT,"valid_to",DataType.TEXT));
    table(d,"__cl_item", cols("item_ref",DataType.TEXT,"version_ref",DataType.TEXT,"item_code",DataType.TEXT,"label_ka",DataType.MEMO,"label_en",DataType.MEMO,"lifecycle_state",DataType.TEXT));
    table(d,"__cl_alias", cols("alias_ref",DataType.TEXT,"item_ref",DataType.TEXT,"source_system",DataType.TEXT,"source_code_raw",DataType.MEMO,"lookup_code_normalized",DataType.MEMO,"normalization_rule",DataType.TEXT,"lifecycle_state",DataType.TEXT));
    table(d,"__cl_hierarchy", cols("version_ref",DataType.TEXT,"parent_item_ref",DataType.TEXT,"child_item_ref",DataType.TEXT,"ordinal",DataType.LONG));
    table(d,"__stat_unit", cols("unit_code",DataType.TEXT,"quantity_kind",DataType.TEXT,"scale_factor",DataType.DOUBLE,"denominator_text",DataType.MEMO,"title",DataType.MEMO));
    table(d,"__stat_metric", cols("metric_code",DataType.TEXT,"source_resource_id",DataType.TEXT,"title_ka",DataType.MEMO,"title_en",DataType.MEMO,"measure_component_code",DataType.TEXT,"unit_code",DataType.TEXT,"aggregation",DataType.TEXT,"lifecycle_state",DataType.TEXT,"inference_confidence",DataType.DOUBLE,"inference_rationale",DataType.MEMO));
    // Raw bytes remain in the immutable uploaded artifact.  This envelope records
    // every fact needed to locate, verify, govern and replay that artifact/row.
    table(d,"__raw_document", cols("source_row_key",DataType.TEXT,"source_table",DataType.TEXT,"source_primary_key",DataType.TEXT,"extract_sequence",DataType.LONG,
      "source_system",DataType.TEXT,"source_feed",DataType.TEXT,"document_identity",DataType.TEXT,"original_filename",DataType.TEXT,
      "mime_type",DataType.TEXT,"byte_size",DataType.LONG,"checksum",DataType.TEXT,"received_at",DataType.TEXT,"source_uri",DataType.MEMO,
      "ingestion_batch",DataType.TEXT,"provenance",DataType.MEMO,"retention_policy",DataType.TEXT,"confidentiality_class",DataType.TEXT,
      "payload_reference",DataType.MEMO,"encryption_reference",DataType.TEXT,"parser_status",DataType.TEXT,"validation_status",DataType.TEXT,
      "supersedes_source_row_key",DataType.TEXT));
    table(d,"__ent_kids_goal", cols("source_goal_id",DataType.TEXT,"category_item_ref",DataType.TEXT,"title_ka",DataType.MEMO,"title_en",DataType.MEMO,"path_ka",DataType.MEMO,"path_en",DataType.MEMO,"source_row_key",DataType.TEXT,"operation",DataType.TEXT));
    table(d,"__ent_kids_resource", cols("source_resource_id",DataType.TEXT,"category_item_ref",DataType.TEXT,"title_ka",DataType.MEMO,"title_en",DataType.MEMO,"path_ka",DataType.MEMO,"path_en",DataType.MEMO,"source_row_key",DataType.TEXT,"operation",DataType.TEXT));
    table(d,"__rel_kids_resource_subcategory_assignment", cols("assignment_key",DataType.TEXT,"source_resource_id",DataType.TEXT,"subcategory_item_ref",DataType.TEXT,"source_token_raw",DataType.MEMO,"ordinal",DataType.LONG,"source_row_key",DataType.TEXT,"operation",DataType.TEXT));
    table(d,"__ent_kids_glossary_entry", cols("source_glossary_id",DataType.TEXT,"language_item_ref",DataType.TEXT,"language_raw",DataType.MEMO,"entry_text",DataType.MEMO,"source_row_key",DataType.TEXT,"operation",DataType.TEXT));
    table(d,"__raw_kids_statistical_carrier", cols("carrier_code",DataType.TEXT,"source_resource_id",DataType.TEXT,"payload_checksum",DataType.TEXT,"parse_status",DataType.TEXT,"source_row_key",DataType.TEXT,"operation",DataType.TEXT));
    table(d,"__stat_kids_statistical_input", cols("input_key",DataType.TEXT,"carrier_code",DataType.TEXT,"cell_ordinal",DataType.LONG,"period_raw",DataType.MEMO,"period_normalized",DataType.TEXT,"dimension_key_raw",DataType.MEMO,"age_group_item_ref",DataType.TEXT,"value_lexical",DataType.MEMO,"value_decimal",DataType.DOUBLE,"json_path",DataType.MEMO,"source_encoding",DataType.TEXT,"source_row_key",DataType.TEXT,"operation",DataType.TEXT));
    table(d,"__rel_kids_statistical_semantic_binding", cols("carrier_code",DataType.TEXT,"metric_code",DataType.TEXT,"unit_code",DataType.TEXT,"aggregation",DataType.TEXT,"obs_status",DataType.TEXT,"conf_status",DataType.TEXT,"quality_policy_code",DataType.TEXT,"confidentiality_policy_code",DataType.TEXT,"inference_method",DataType.TEXT,"operation",DataType.TEXT));
    declareContract(d);
    addPhysicalIndexes(d);
  }
  private static void declareContract(Database d)throws Exception {
    Table ds=d.getTable("__gs_dataset"), f=d.getTable("__gs_field"), k=d.getTable("__gs_key"), r=d.getTable("__gs_relation"), p=d.getTable("__gs_projection"), pages=d.getTable("__gs_page");
    dataset(ds,f,k,"KIDS_CLASSIFIER_SCHEME","__cl_scheme","REFERENCE","one classifier scheme","scheme_code",new String[][]{{"scheme_code","CODE","NATURAL_KEY"},{"authority_mode","CODE","ATTRIBUTE"},{"title","TEXT","CONTENT"},{"standard_reference","TEXT","ATTRIBUTE"}});
    dataset(ds,f,k,"KIDS_CLASSIFIER_VERSION","__cl_version","REFERENCE","one classifier scheme version","version_ref",new String[][]{{"version_ref","CODE","NATURAL_KEY"},{"scheme_code","CODE","FOREIGN_KEY"},{"version_code","CODE","ATTRIBUTE"},{"lifecycle_state","CODE","ATTRIBUTE"},{"valid_from","DATE","ATTRIBUTE"},{"valid_to","DATE","ATTRIBUTE"}});
    dataset(ds,f,k,"KIDS_CLASSIFIER_ITEM","__cl_item","REFERENCE","one versioned classifier item","item_ref",new String[][]{{"item_ref","CODE","NATURAL_KEY"},{"version_ref","CODE","FOREIGN_KEY"},{"item_code","CODE","ATTRIBUTE"},{"label_ka","TEXT","LOCALIZED_TEXT"},{"label_en","TEXT","LOCALIZED_TEXT"},{"lifecycle_state","CODE","ATTRIBUTE"}});
    dataset(ds,f,k,"KIDS_CLASSIFIER_ALIAS","__cl_alias","REFERENCE","one external classifier alias","alias_ref",new String[][]{{"alias_ref","CODE","NATURAL_KEY"},{"item_ref","CODE","FOREIGN_KEY"},{"source_system","CODE","ATTRIBUTE"},{"source_code_raw","TEXT","RAW_PAYLOAD"},{"lookup_code_normalized","TEXT","ATTRIBUTE"},{"normalization_rule","CODE","ATTRIBUTE"},{"lifecycle_state","CODE","ATTRIBUTE"}});
    dataset(ds,f,k,"KIDS_CLASSIFIER_HIERARCHY","__cl_hierarchy","REFERENCE","one classifier parent child edge","child_item_ref",new String[][]{{"version_ref","CODE","FOREIGN_KEY"},{"parent_item_ref","CODE","FOREIGN_KEY"},{"child_item_ref","CODE","NATURAL_KEY"},{"ordinal","INTEGER","ATTRIBUTE"}});
    dataset(ds,f,k,"KIDS_STATISTICAL_UNIT","__stat_unit","REFERENCE","one governed statistical unit","unit_code",new String[][]{{"unit_code","CODE","NATURAL_KEY"},{"quantity_kind","CODE","ATTRIBUTE"},{"scale_factor","DECIMAL","ATTRIBUTE"},{"denominator_text","TEXT","ATTRIBUTE"},{"title","TEXT","CONTENT"}});
    dataset(ds,f,k,"KIDS_STATISTICAL_METRIC","__stat_metric","REFERENCE","one carrier-specific governed metric","metric_code",new String[][]{{"metric_code","CODE","NATURAL_KEY"},{"source_resource_id","CODE","FOREIGN_KEY"},{"title_ka","TEXT","LOCALIZED_TEXT"},{"title_en","TEXT","LOCALIZED_TEXT"},{"measure_component_code","CODE","ATTRIBUTE"},{"unit_code","CODE","FOREIGN_KEY"},{"aggregation","CODE","ATTRIBUTE"},{"lifecycle_state","CODE","ATTRIBUTE"},{"inference_confidence","DECIMAL","ATTRIBUTE"},{"inference_rationale","TEXT","ATTRIBUTE"}});
    dataset(ds,f,k,"KIDS_RAW_DOCUMENT","__raw_document","RAW","immutable artifact envelope and stable source-row locator","source_row_key",new String[][]{{"source_row_key","CODE","NATURAL_KEY"},{"source_table","CODE","ATTRIBUTE"},{"source_primary_key","CODE","ATTRIBUTE"},{"extract_sequence","INTEGER","ATTRIBUTE"},{"source_system","CODE","PROVENANCE"},{"source_feed","CODE","PROVENANCE"},{"document_identity","CODE","PROVENANCE"},{"original_filename","TEXT","PROVENANCE"},{"mime_type","CODE","PROVENANCE"},{"byte_size","INTEGER","PROVENANCE"},{"checksum","CODE","PROVENANCE"},{"received_at","DATE","PROVENANCE"},{"source_uri","URI","PROVENANCE"},{"ingestion_batch","CODE","PROVENANCE"},{"provenance","TEXT","PROVENANCE"},{"retention_policy","CODE","GOVERNANCE"},{"confidentiality_class","CODE","GOVERNANCE"},{"payload_reference","URI","PROVENANCE"},{"encryption_reference","CODE","GOVERNANCE"},{"parser_status","CODE","QUALITY"},{"validation_status","CODE","QUALITY"},{"supersedes_source_row_key","CODE","LINEAGE"}});
    dataset(ds,f,k,"KIDS_GOAL","kids_goal","ENTITY","one KIDS goal","source_goal_id",new String[][]{{"source_goal_id","CODE","NATURAL_KEY"},{"category_item_ref","CODE","CLASSIFICATION"},{"title_ka","TEXT","LOCALIZED_TEXT"},{"title_en","TEXT","LOCALIZED_TEXT"},{"path_ka","URI","LOCATOR"},{"path_en","URI","LOCATOR"},{"source_row_key","CODE","FOREIGN_KEY"},{"operation","CODE","ATTRIBUTE"}});
    dataset(ds,f,k,"KIDS_RESOURCE","kids_resource","ENTITY","one KIDS file resource","source_resource_id",new String[][]{{"source_resource_id","CODE","NATURAL_KEY"},{"category_item_ref","CODE","CLASSIFICATION"},{"title_ka","TEXT","LOCALIZED_TEXT"},{"title_en","TEXT","LOCALIZED_TEXT"},{"path_ka","URI","LOCATOR"},{"path_en","URI","LOCATOR"},{"source_row_key","CODE","FOREIGN_KEY"},{"operation","CODE","ATTRIBUTE"}});
    dataset(ds,f,k,"KIDS_RESOURCE_SUBCATEGORY_ASSIGNMENT","kids_resource_subcategory_assignment","RELATION","one resource subcategory token","assignment_key",new String[][]{{"assignment_key","CODE","NATURAL_KEY"},{"source_resource_id","CODE","FOREIGN_KEY"},{"subcategory_item_ref","CODE","CLASSIFICATION"},{"source_token_raw","TEXT","RAW_PAYLOAD"},{"ordinal","INTEGER","ATTRIBUTE"},{"source_row_key","CODE","FOREIGN_KEY"},{"operation","CODE","ATTRIBUTE"}});
    dataset(ds,f,k,"KIDS_GLOSSARY_ENTRY","kids_glossary_entry","ENTITY","one independent glossary entry","source_glossary_id",new String[][]{{"source_glossary_id","CODE","NATURAL_KEY"},{"language_item_ref","CODE","CLASSIFICATION"},{"language_raw","TEXT","RAW_PAYLOAD"},{"entry_text","TEXT","CONTENT"},{"source_row_key","CODE","FOREIGN_KEY"},{"operation","CODE","ATTRIBUTE"}});
    dataset(ds,f,k,"KIDS_STATISTICAL_CARRIER","kids_statistical_carrier","RAW","one resource-bound statistical carrier locator","carrier_code",new String[][]{{"carrier_code","CODE","NATURAL_KEY"},{"source_resource_id","CODE","FOREIGN_KEY"},{"payload_checksum","CODE","ATTRIBUTE"},{"parse_status","CODE","ATTRIBUTE"},{"source_row_key","CODE","FOREIGN_KEY"},{"operation","CODE","ATTRIBUTE"}});
    dataset(ds,f,k,"KIDS_STATISTICAL_INPUT","kids_statistical_input","STATISTICAL","one parsed source statistical cell","input_key",new String[][]{{"input_key","CODE","IDENTIFIER"},{"carrier_code","CODE","FOREIGN_KEY"},{"cell_ordinal","INTEGER","ATTRIBUTE"},{"period_raw","TEXT","PERIOD"},{"period_normalized","TEXT","PERIOD"},{"dimension_key_raw","TEXT","RAW_PAYLOAD"},{"age_group_item_ref","CODE","DIMENSION"},{"value_lexical","TEXT","RAW_PAYLOAD"},{"value_decimal","DECIMAL","MEASURE"},{"json_path","TEXT","ATTRIBUTE"},{"source_encoding","CODE","ATTRIBUTE"},{"source_row_key","CODE","FOREIGN_KEY"},{"operation","CODE","ATTRIBUTE"}});
    k.addRow("KIDS_STATISTICAL_INPUT","carrier_code","NATURAL","1"); k.addRow("KIDS_STATISTICAL_INPUT","cell_ordinal","NATURAL","2");
    dataset(ds,f,k,"KIDS_STATISTICAL_SEMANTIC_BINDING","kids_statistical_semantic_binding","RELATION","one approved semantic binding per carrier","carrier_code",new String[][]{{"carrier_code","CODE","NATURAL_KEY"},{"metric_code","CODE","FOREIGN_KEY"},{"unit_code","CODE","FOREIGN_KEY"},{"aggregation","CODE","ATTRIBUTE"},{"obs_status","CODE","ATTRIBUTE"},{"conf_status","CODE","ATTRIBUTE"},{"quality_policy_code","CODE","ATTRIBUTE"},{"confidentiality_policy_code","CODE","ATTRIBUTE"},{"inference_method","CODE","ATTRIBUTE"},{"operation","CODE","ATTRIBUTE"}});
    rel(r,"VERSION_FOR_SCHEME","KIDS_CLASSIFIER_VERSION","scheme_code","KIDS_CLASSIFIER_SCHEME","scheme_code","MANY_TO_ONE"); rel(r,"ITEM_FOR_VERSION","KIDS_CLASSIFIER_ITEM","version_ref","KIDS_CLASSIFIER_VERSION","version_ref","MANY_TO_ONE"); rel(r,"ALIAS_FOR_ITEM","KIDS_CLASSIFIER_ALIAS","item_ref","KIDS_CLASSIFIER_ITEM","item_ref","MANY_TO_ONE");
    rel(r,"GOAL_CATEGORY","KIDS_GOAL","category_item_ref","KIDS_CLASSIFIER_ITEM","item_ref","MANY_TO_ONE"); rel(r,"RESOURCE_CATEGORY","KIDS_RESOURCE","category_item_ref","KIDS_CLASSIFIER_ITEM","item_ref","MANY_TO_ONE"); rel(r,"SUBCATEGORY_FOR_RESOURCE","KIDS_RESOURCE_SUBCATEGORY_ASSIGNMENT","source_resource_id","KIDS_RESOURCE","source_resource_id","MANY_TO_ONE"); rel(r,"SUBCATEGORY_ITEM","KIDS_RESOURCE_SUBCATEGORY_ASSIGNMENT","subcategory_item_ref","KIDS_CLASSIFIER_ITEM","item_ref","MANY_TO_ONE"); rel(r,"GLOSSARY_LANGUAGE","KIDS_GLOSSARY_ENTRY","language_item_ref","KIDS_CLASSIFIER_ITEM","item_ref","MANY_TO_ONE"); rel(r,"CARRIER_FOR_RESOURCE","KIDS_STATISTICAL_CARRIER","source_resource_id","KIDS_RESOURCE","source_resource_id","ONE_TO_ONE"); rel(r,"INPUT_FOR_CARRIER","KIDS_STATISTICAL_INPUT","carrier_code","KIDS_STATISTICAL_CARRIER","carrier_code","MANY_TO_ONE");
    rel(r,"METRIC_FOR_RESOURCE","KIDS_STATISTICAL_METRIC","source_resource_id","KIDS_RESOURCE","source_resource_id","ONE_TO_ONE"); rel(r,"METRIC_UNIT","KIDS_STATISTICAL_METRIC","unit_code","KIDS_STATISTICAL_UNIT","unit_code","MANY_TO_ONE"); rel(r,"SEMANTIC_FOR_CARRIER","KIDS_STATISTICAL_SEMANTIC_BINDING","carrier_code","KIDS_STATISTICAL_CARRIER","carrier_code","ONE_TO_ONE"); rel(r,"SEMANTIC_METRIC","KIDS_STATISTICAL_SEMANTIC_BINDING","metric_code","KIDS_STATISTICAL_METRIC","metric_code","MANY_TO_ONE"); rel(r,"SEMANTIC_UNIT","KIDS_STATISTICAL_SEMANTIC_BINDING","unit_code","KIDS_STATISTICAL_UNIT","unit_code","MANY_TO_ONE");
    rel(r,"GOAL_RAW_LINEAGE","KIDS_GOAL","source_row_key","KIDS_RAW_DOCUMENT","source_row_key","MANY_TO_ONE"); rel(r,"RESOURCE_RAW_LINEAGE","KIDS_RESOURCE","source_row_key","KIDS_RAW_DOCUMENT","source_row_key","MANY_TO_ONE"); rel(r,"SUBCATEGORY_RAW_LINEAGE","KIDS_RESOURCE_SUBCATEGORY_ASSIGNMENT","source_row_key","KIDS_RAW_DOCUMENT","source_row_key","MANY_TO_ONE"); rel(r,"GLOSSARY_RAW_LINEAGE","KIDS_GLOSSARY_ENTRY","source_row_key","KIDS_RAW_DOCUMENT","source_row_key","MANY_TO_ONE"); rel(r,"CARRIER_RAW_LINEAGE","KIDS_STATISTICAL_CARRIER","source_row_key","KIDS_RAW_DOCUMENT","source_row_key","MANY_TO_ONE"); rel(r,"INPUT_RAW_LINEAGE","KIDS_STATISTICAL_INPUT","source_row_key","KIDS_RAW_DOCUMENT","source_row_key","MANY_TO_ONE");
    p.addRow("KIDS_GOAL_ENTITY","KIDS_GOAL","ENTITY","{\"approvalState\":\"READY\",\"lineageRequired\":true,\"approvedBy\":\"USER_AUTHORITY\",\"approvalBasis\":\"PAGE_8_GOALS_PARITY_2026_09_15\"}","READY");
    for(String dataset:new String[]{"KIDS_RESOURCE","KIDS_GLOSSARY_ENTRY"}) p.addRow(dataset+"_ENTITY",dataset,"ENTITY","{\"approvalState\":\"DRAFT\",\"lineageRequired\":true}","DRAFT");
    p.addRow("KIDS_SUBCATEGORY_RELATION","KIDS_RESOURCE_SUBCATEGORY_ASSIGNMENT","RELATION","{\"approvalState\":\"DRAFT\",\"requiresClassifierReview\":true}","DRAFT");
    p.addRow("KIDS_STATS_INPUT","KIDS_STATISTICAL_INPUT","STATISTICAL","{\"contractRevision\":8,\"approvalState\":\"READY\",\"approvalBasis\":\"DELEGATED_OWNER_AUTHORIZATION_2026_09_10\",\"projectionModel\":\"SDMX_COMPATIBLE_LONG\",\"semanticBindingDataset\":\"KIDS_STATISTICAL_SEMANTIC_BINDING\",\"metricLookup\":{\"metricCodePattern\":\"KIDS_FILE_{resourceId}\"},\"ageClassificationSystem\":\"KIDS_R7_AGE_GROUP\",\"dataflow\":{\"code\":\"KIDS_FILES_STATISTICS\",\"sourceDataset\":\"KIDS_RESOURCE\"},\"dsd\":{\"code\":\"KIDS_FILES_STATISTICS_DSD\",\"revision\":2,\"observationGrain\":[\"carrier_code\",\"cell_ordinal\"],\"components\":[{\"code\":\"TIME_PERIOD\",\"role\":\"DIMENSION\",\"sourceField\":\"period_raw\"},{\"code\":\"AGE_GROUP\",\"role\":\"DIMENSION\",\"sourceField\":\"age_group_item_ref\"},{\"code\":\"OBS_VALUE\",\"role\":\"PRIMARY_MEASURE\",\"sourceField\":\"value_decimal\"}],\"attributesFromBinding\":[\"metric_code\",\"unit_code\",\"aggregation\",\"obs_status\",\"conf_status\"]},\"qualityPolicy\":\"KIDS_AGGREGATE_QUALITY_V1\",\"confidentialityPolicy\":\"KIDS_PUBLIC_AGGREGATE_V1\",\"overlappingAgeGroups\":true,\"aggregationDefault\":\"NONE\",\"lineage\":{\"rawArtifactAuthority\":\"IMMUTABLE_OBJECT_STORAGE\"}}","READY");
    p.addRow("KIDS_CLASSIFIER_ITEM","KIDS_CLASSIFIER_ITEM","REFERENCE","{\"contractRevision\":8,\"approvalState\":\"READY\",\"projectionModel\":\"REFERENCE_REGISTRY\",\"lineage\":{\"rawArtifactAuthority\":\"IMMUTABLE_OBJECT_STORAGE\"}}","READY");
    pages.addRow("KIDS_ROOT","KIDS_ROOT","KIDS_PORTAL_V1","8",null,"SITE_ROOT","","kids","",1,"true","READY");
    pages.addRow("KIDS_GOALS","KIDS_GOALS","KIDS_PORTAL_V1","8","KIDS_ROOT","ENTITY_COLLECTION","KIDS_GOAL","goals","KIDS_GOAL_ENTITY",10,"true","READY");
    pages.addRow("KIDS_RESOURCES","KIDS_RESOURCES","KIDS_PORTAL_V1","8","KIDS_ROOT","ENTITY_COLLECTION","KIDS_RESOURCE","resources","KIDS_RESOURCE_ENTITY",20,"true","READY");
    pages.addRow("KIDS_GLOSSARY","KIDS_GLOSSARY","KIDS_PORTAL_V1","8","KIDS_ROOT","ENTITY_COLLECTION","KIDS_GLOSSARY_ENTRY","glossary","KIDS_GLOSSARY_ENTRY_ENTITY",30,"true","READY");
    pages.addRow("KIDS_STATISTICS","KIDS_STATISTICS","KIDS_PORTAL_V1","8","KIDS_ROOT","STATISTICAL_DATAFLOW","KIDS_STATISTICAL_INPUT","statistics","KIDS_STATS_INPUT",40,"true","READY");
    pages.addRow("KIDS_CLASSIFIERS","KIDS_CLASSIFIERS","KIDS_PORTAL_V1","8","KIDS_ROOT","REFERENCE_REGISTRY","KIDS_CLASSIFIER_ITEM","classifiers","",50,"true","READY");
    d.getTable("__gs_metadata_schema").addRow("CORE_RESOURCE_V1","CORE","1","{\"type\":\"object\",\"properties\":{\"title\":{\"type\":\"localizedText\"},\"description\":{\"type\":\"localizedText\"}}}","READY");
    d.getTable("__gs_metadata_schema").addRow("VISUALIZATION_V1","PRESENTATION","1","{\"type\":\"object\",\"properties\":{\"title\":{\"type\":\"localizedText\"},\"description\":{\"type\":\"localizedText\"},\"chartType\":{\"type\":\"CODE\"}}}","READY");
  }
  private static void load(Database d,Database legacy)throws Exception {
    Map<String,String> category=new HashMap<>(); int seq=0;
    addUnits(d);
    addScheme(d,SCHEME_GOAL,"PROPOSAL","KIDS source goal categories"); addScheme(d,SCHEME_LANGUAGE,"PROPOSAL","KIDS source languages"); addScheme(d,SCHEME_SUB,"PROPOSAL","KIDS resource subcategories"); addScheme(d,SCHEME_AGE,"PROPOSAL","KIDS chart age-group keys");
    for(Row row:legacy.getTable("goals_titles")){String id=s(row,"ID"), code=s(row,"category"); String ref=item(d,SCHEME_GOAL,code,s(row,"title_geo"),s(row,"title_eng"),"DRAFT"); category.put(id,ref); raw(d,"goals_titles",id,row,++seq); alias(d,ref,"KIDS_LEGACY_ACCESS",code,code,"NONE","DRAFT");}
    for(Row row:legacy.getTable("goals")){String id=s(row,"ID"), raw=raw(d,"goals",id,row,++seq); d.getTable("__ent_kids_goal").addRow(id,requiredRef(category,s(row,"category"),"goals",id),s(row,"title_geo"),s(row,"title_eng"),s(row,"path_geo"),s(row,"path_eng"),raw,"UPSERT");}
    Set<String> subs=new HashSet<>(), ages=new HashSet<>();
    for(Row row:legacy.getTable("files")){String id=s(row,"ID"), raw=raw(d,"files",id,row,++seq); d.getTable("__ent_kids_resource").addRow(id,requiredRef(category,s(row,"category"),"files",id),s(row,"title_geo"),s(row,"title_eng"),s(row,"path_geo"),s(row,"path_eng"),raw,"UPSERT"); int ordinal=0; for(String token:s(row,"sub_category").split(",",-1)){if(token.isEmpty())continue; String normalized=token.trim(); if(normalized.isEmpty())continue; String ref=subs.add(normalized)?item(d,SCHEME_SUB,normalized,null,null,"DRAFT"):itemRef(SCHEME_SUB,normalized); alias(d,ref,"KIDS_LEGACY_ACCESS",token,normalized,token.equals(normalized)?"NONE":"TRIM_FOR_LOOKUP_ONLY","DRAFT"); d.getTable("__rel_kids_resource_subcategory_assignment").addRow(id+"|"+(++ordinal),id,ref,token,ordinal,raw,"UPSERT");} carrierAndInputs(d,row,id,raw,ages);}
    Set<String> languages=new HashSet<>(); for(Row row:legacy.getTable("glossary")){String id=s(row,"ID"), lang=s(row,"lang"); String ref=languages.add(lang)?item(d,SCHEME_LANGUAGE,lang,lang.equals("ka")?"ქართული":null,lang.equals("en")?"English":null,lang.equals("ena")?"DRAFT":"READY"):itemRef(SCHEME_LANGUAGE,lang); alias(d,ref,"KIDS_LEGACY_ACCESS",lang,lang,"NONE",lang.equals("ena")?"DRAFT":"READY"); String raw=raw(d,"glossary",id,row,++seq);d.getTable("__ent_kids_glossary_entry").addRow(id,ref,lang,s(row,"text"),raw,"UPSERT");}
  }
  private static void populateMetadata(Database d)throws Exception {
    Table t=d.getTable("__gs_metadata");
    String[][] pages={{"KIDS_ROOT","ბავშვებისა და მოზარდების სტატისტიკა","Children and youth statistics"},{"KIDS_GOALS","მიზნები","Goals"},{"KIDS_RESOURCES","რესურსები","Resources"},{"KIDS_GLOSSARY","ლექსიკონი","Glossary"},{"KIDS_STATISTICS","სტატისტიკა","Statistics"},{"KIDS_CLASSIFIERS","კლასიფიკატორები","Classifiers"}};
    for(String[] p:pages){meta(t,"PAGE",p[0],8,"CORE","title","ka","TEXT",p[1],null,1,"READY","__gs_page|"+p[0]);meta(t,"PAGE",p[0],8,"CORE","title","en","TEXT",p[2],null,1,"READY","__gs_page|"+p[0]);}
    for(Row r:d.getTable("__stat_unit")){String code=s(r,"unit_code");meta(t,"UNIT",code,1,"CORE","title",null,"TEXT",s(r,"title"),null,1,"READY","__stat_unit|"+code);meta(t,"UNIT",code,1,"SEMANTIC","quantityKind",null,"CODE",s(r,"quantity_kind"),null,1,"READY","__stat_unit|"+code);}
    for(Row r:d.getTable("__stat_metric")){String code=s(r,"metric_code");meta(t,"METRIC",code,1,"CORE","title","ka","TEXT",s(r,"title_ka"),null,1,"READY","__stat_metric|"+code);meta(t,"METRIC",code,1,"CORE","title","en","TEXT",s(r,"title_en"),null,1,"READY","__stat_metric|"+code);meta(t,"METRIC",code,1,"SEMANTIC","unitCode",null,"CODE",s(r,"unit_code"),null,1,"READY","__stat_metric|"+code);meta(t,"METRIC",code,1,"SEMANTIC","aggregation",null,"CODE",s(r,"aggregation"),null,1,"READY","__stat_metric|"+code);meta(t,"METRIC",code,1,"PROVENANCE","inferenceRationale",null,"TEXT",s(r,"inference_rationale"),null,1,"READY","__stat_metric|"+code);}
    for(Row r:d.getTable("__cl_scheme")){String code=s(r,"scheme_code");meta(t,"CLASSIFIER_SCHEME",code,1,"CORE","title",null,"TEXT",s(r,"title"),null,1,"READY","__cl_scheme|"+code);meta(t,"CLASSIFIER_SCHEME",code,1,"PROVENANCE","standardReference",null,"URI",s(r,"standard_reference"),null,1,"READY","__cl_scheme|"+code);}
    for(Row r:d.getTable("__gs_projection")){String code=s(r,"projection_code");meta(t,"PROJECTION",code,1,"PRESENTATION","projectionFamily",null,"CODE",s(r,"projection_family"),null,1,"READY","__gs_projection|"+code);meta(t,"PROJECTION",code,1,"SEMANTIC","mapping",null,"JSON",null,s(r,"mapping_json"),1,"READY","__gs_projection|"+code);}
  }
  private static void meta(Table t,String type,String subject,int rev,String ns,String prop,String lang,String valueType,String text,String json,int ordinal,String state,String source)throws Exception {t.addRow(type,subject,String.valueOf(rev),ns,prop,lang==null?"":lang,valueType,text==null?"":text,json,ordinal,state,source);}
  private static void carrierAndInputs(Database d,Row row,String id,String sourceRow,Set<String> ages)throws Exception {String payload=s(row,"chartdata"); if(payload.isBlank())return; String carrier="CARRIER|"+id; JsonNode array=null; String enc="DIRECT_JSON"; try{array=JSON.readTree(payload);}catch(Exception x){try{array=JSON.readTree(JSON.readValue("\""+payload.replace("\"","\\\"")+"\"",String.class));enc="ESCAPED_JSON_TEXT";}catch(Exception ignored){}} if(array==null||!array.isArray())return; Semantic semantic=SEMANTICS.get(id);if(semantic==null)throw new IllegalStateException("Missing governed semantic inference for carrier resource "+id);d.getTable("__raw_kids_statistical_carrier").addRow(carrier,id,sha(payload),"PARSED_ARRAY",sourceRow,"UPSERT");d.getTable("__stat_metric").addRow(semantic.metric(),id,s(row,"title_geo"),s(row,"title_eng"),"OBS_VALUE",semantic.unit(),"NONE","PROVISIONAL_APPROVED",semantic.confidence(),semantic.rationale());d.getTable("__rel_kids_statistical_semantic_binding").addRow(carrier,semantic.metric(),semantic.unit(),"NONE","A","F","KIDS_AGGREGATE_QUALITY_V1","KIDS_PUBLIC_AGGREGATE_V1","TITLE_RANGE_STANDARD_INFERENCE","UPSERT");int ordinal=0; for(int i=0;i<array.size();i++){JsonNode object=array.get(i);if(!object.isObject())continue;String period=object.path("year").asText();for(Iterator<Map.Entry<String,JsonNode>> it=object.fields();it.hasNext();){Map.Entry<String,JsonNode> e=it.next();if("year".equals(e.getKey())||e.getValue().isNull())continue;String key=e.getKey(),ref=ages.add(key)?item(d,SCHEME_AGE,key,null,null,"DRAFT"):itemRef(SCHEME_AGE,key);alias(d,ref,"KIDS_LEGACY_ACCESS",key,key.trim(),key.equals(key.trim())?"NONE":"TRIM_FOR_LOOKUP_ONLY","DRAFT");String lexical=e.getValue().asText();Double number;try{number=Double.valueOf(lexical);}catch(Exception ignored){number=null;}int n=++ordinal;d.getTable("__stat_kids_statistical_input").addRow(carrier+"|"+n,carrier,n,period,period.matches("[0-9]{4}")?period:null,key,ref,lexical,number,"$["+i+"]."+key,enc,sourceRow,"UPSERT");}}}
  private static void addUnits(Database d)throws Exception{Table t=d.getTable("__stat_unit");t.addRow("COUNT_EVENT","EVENT",1d,null,"Count of events");t.addRow("COUNT_CASE","CASE",1d,null,"Count of cases");t.addRow("PERSON","PERSON",1d,null,"Persons");t.addRow("THOUSAND_PERSONS","PERSON",1000d,null,"Thousand persons");t.addRow("THOUSAND_VISITS","VISIT",1000d,null,"Thousand visits");t.addRow("AVERAGE_NIGHTS","NIGHT",1d,"per visit","Average nights per visit");t.addRow("PER_100000_LIVE_BIRTHS","RATIO",1d,"100,000 live births","Per 100,000 live births");t.addRow("PER_1000_UNINFECTED_POPULATION","RATIO",1d,"1,000 uninfected population","Per 1,000 uninfected population");t.addRow("PER_100000_POPULATION","RATIO",1d,"100,000 population","Per 100,000 population");t.addRow("PERCENT","RATIO",.01d,"100 population","Percent");}
  private static void addScheme(Database d,String code,String mode,String title)throws Exception {d.getTable("__cl_scheme").addRow(code,mode,title,"ISO/IEC 11179 compatible managed value domain");d.getTable("__cl_version").addRow(versionRef(code),code,VERSION,"DRAFT","2026-09-09",null);}
  private static String item(Database d,String scheme,String code,String ka,String en,String state)throws Exception {String ref=itemRef(scheme,code);try{d.getTable("__cl_item").addRow(ref,versionRef(scheme),code,ka,en,state);}catch(ConstraintViolationException ignored){}return ref;}
  private static void alias(Database d,String item,String source,String raw,String normal,String rule,String state)throws Exception {String ref="ALIAS|"+item+"|"+sha(raw);try{d.getTable("__cl_alias").addRow(ref,item,source,raw,normal,rule,state);}catch(ConstraintViolationException ignored){}}
  private static String raw(Database d,String table,String pk,Row row,int seq)throws Exception {String key=table+"|"+pk;String fileName=SOURCE_ARTIFACT==null?"":SOURCE_ARTIFACT.getName();String received=SOURCE_ARTIFACT==null?"":java.time.Instant.ofEpochMilli(SOURCE_ARTIFACT.lastModified()).toString();d.getTable("__raw_document").addRow(key,table,pk,seq,"KIDS_LEGACY_ACCESS","KIDS_PORTAL_EXPORT","KIDS_PORTAL_V1|R8|"+fileName,fileName,"application/vnd.ms-access",SOURCE_ARTIFACT==null?0:SOURCE_ARTIFACT.length(),SOURCE_CHECKSUM,received,SOURCE_ARTIFACT==null?"":SOURCE_ARTIFACT.getAbsolutePath(),"kids-portal-canonical-r8","{\"method\":\"read_only_access_extract\",\"sourceTable\":\""+table+"\",\"sourcePrimaryKey\":\""+pk+"\"}","ARCHIVE_1Y","PUBLIC_AGGREGATE","artifact://kids-portal-canonical-r8/"+fileName,"NONE","PARSED","PENDING","");return key;}
  private static String shaFile(File file)throws Exception{MessageDigest md=MessageDigest.getInstance("SHA-256");try(java.io.InputStream in=new java.io.FileInputStream(file)){byte[] buf=new byte[8192];for(int n;(n=in.read(buf))>0;)md.update(buf,0,n);}StringBuilder b=new StringBuilder();for(byte x:md.digest())b.append(String.format("%02x",x));return b.toString();}
  private static String versionRef(String scheme){return scheme+"|"+VERSION;} private static String itemRef(String scheme,String code){return versionRef(scheme)+"|"+code;} private static String s(Row r,String c){Object v=r.get(c);return v==null?"":String.valueOf(v);} private static String sha(String value)throws Exception{byte[] hash=MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();for(byte x:hash)b.append(String.format("%02x",x));return b.toString();}
  private static String requiredRef(Map<String,String> refs,String code,String table,String id){String ref=refs.get(code);if(ref==null)throw new IllegalStateException("Unresolved category in "+table+" ID="+id+": "+code);return ref;}
  private static void addPhysicalIndexes(Database d)throws Exception {
    primary(d,"__gs_package","package_code"); primary(d,"__gs_dataset","dataset_code"); primary(d,"__gs_field","dataset_code","field_name"); primary(d,"__gs_key","dataset_code","key_role","key_order"); primary(d,"__gs_relation","relationship_code"); primary(d,"__gs_projection","projection_code"); primary(d,"__gs_metadata_schema","schema_code"); primary(d,"__gs_metadata","subject_type","subject_code","subject_revision","namespace_code","property_code","language_tag","ordinal"); primary(d,"__gs_page","page_code");
    primary(d,"__cl_scheme","scheme_code"); primary(d,"__cl_version","version_ref"); primary(d,"__cl_item","item_ref"); primary(d,"__cl_alias","alias_ref"); primary(d,"__cl_hierarchy","child_item_ref"); primary(d,"__stat_unit","unit_code"); primary(d,"__stat_metric","metric_code");
    primary(d,"__raw_document","source_row_key"); primary(d,"kids_goal","source_goal_id"); primary(d,"kids_resource","source_resource_id"); primary(d,"kids_resource_subcategory_assignment","assignment_key"); primary(d,"kids_glossary_entry","source_glossary_id"); primary(d,"kids_statistical_carrier","carrier_code"); primary(d,"kids_statistical_input","input_key"); primary(d,"kids_statistical_semantic_binding","carrier_code");
    unique(d,"UX_cl_version_code","__cl_version","scheme_code","version_code"); unique(d,"UX_cl_item_code","__cl_item","version_ref","item_code"); unique(d,"UX_raw_source","__raw_document","source_table","source_primary_key"); unique(d,"UX_sub_assignment","kids_resource_subcategory_assignment","source_resource_id","ordinal"); unique(d,"UX_carrier_resource","kids_statistical_carrier","source_resource_id"); unique(d,"UX_input_ordinal","kids_statistical_input","carrier_code","cell_ordinal"); unique(d,"UX_metric_resource","__stat_metric","source_resource_id");
  }
  private static void addPhysicalRelationships(Database d)throws Exception {
    relationship(d,"FK_cl_version_scheme","__cl_scheme","scheme_code","__cl_version","scheme_code"); relationship(d,"FK_cl_item_version","__cl_version","version_ref","__cl_item","version_ref"); relationship(d,"FK_cl_alias_item","__cl_item","item_ref","__cl_alias","item_ref");
    relationship(d,"FK_goal_category","__cl_item","item_ref","kids_goal","category_item_ref"); relationship(d,"FK_resource_category","__cl_item","item_ref","kids_resource","category_item_ref"); relationship(d,"FK_sub_resource","kids_resource","source_resource_id","kids_resource_subcategory_assignment","source_resource_id"); relationship(d,"FK_sub_item","__cl_item","item_ref","kids_resource_subcategory_assignment","subcategory_item_ref"); relationship(d,"FK_glossary_language","__cl_item","item_ref","kids_glossary_entry","language_item_ref"); relationship(d,"FK_carrier_resource","kids_resource","source_resource_id","kids_statistical_carrier","source_resource_id"); relationship(d,"FK_input_carrier","kids_statistical_carrier","carrier_code","kids_statistical_input","carrier_code");
    relationship(d,"FK_metric_resource","kids_resource","source_resource_id","__stat_metric","source_resource_id"); relationship(d,"FK_metric_unit","__stat_unit","unit_code","__stat_metric","unit_code"); relationship(d,"FK_semantic_carrier","kids_statistical_carrier","carrier_code","kids_statistical_semantic_binding","carrier_code"); relationship(d,"FK_semantic_metric","__stat_metric","metric_code","kids_statistical_semantic_binding","metric_code"); relationship(d,"FK_semantic_unit","__stat_unit","unit_code","kids_statistical_semantic_binding","unit_code");
    relationship(d,"FK_goal_raw","__raw_document","source_row_key","kids_goal","source_row_key"); relationship(d,"FK_resource_raw","__raw_document","source_row_key","kids_resource","source_row_key"); relationship(d,"FK_sub_raw","__raw_document","source_row_key","kids_resource_subcategory_assignment","source_row_key"); relationship(d,"FK_glossary_raw","__raw_document","source_row_key","kids_glossary_entry","source_row_key"); relationship(d,"FK_carrier_raw","__raw_document","source_row_key","kids_statistical_carrier","source_row_key"); relationship(d,"FK_input_raw","__raw_document","source_row_key","kids_statistical_input","source_row_key");
  }
  private static void verify(Database d,Database source)throws Exception {long goals=count(source,"goals"),resources=count(source,"files"),glossary=count(source,"glossary"),categories=count(source,"goals_titles");expect(d,"__raw_document",goals+resources+glossary+categories);expect(d,"kids_goal",goals);expect(d,"kids_resource",resources);expect(d,"kids_glossary_entry",glossary);long carriers=count(d,"kids_statistical_carrier");expect(d,"__stat_metric",carriers);expect(d,"kids_statistical_semantic_binding",carriers);if(count(d,"__stat_unit")!=10||count(d,"kids_resource_subcategory_assignment")==0||carriers==0||count(d,"kids_statistical_input")==0)throw new IllegalStateException("Canonical reference/relation/statistical datasets are empty");if(carriers>resources)throw new IllegalStateException("A resource cannot have more than one statistical carrier");if(d.getRelationships().size()!=21)throw new IllegalStateException("Expected 21 enforced Access relationships, got "+d.getRelationships().size());}
  private static String accessTable(String table){return switch(table){case "kids_goal"->"__ent_kids_goal";case "kids_resource"->"__ent_kids_resource";case "kids_resource_subcategory_assignment"->"__rel_kids_resource_subcategory_assignment";case "kids_glossary_entry"->"__ent_kids_glossary_entry";case "kids_statistical_carrier"->"__raw_kids_statistical_carrier";case "kids_statistical_input"->"__stat_kids_statistical_input";case "kids_statistical_semantic_binding"->"__rel_kids_statistical_semantic_binding";default->table;};}
  private static long count(Database d,String table)throws Exception{long n=0;for(Row ignored:d.getTable(accessTable(table)))n++;return n;} private static void expect(Database d,String table,long expected)throws Exception{long actual=count(d,table);if(actual!=expected)throw new IllegalStateException(table+" expected "+expected+" rows, got "+actual);}
  private static void primary(Database d,String table,String... columns)throws Exception{String actual=accessTable(table);new IndexBuilder(IndexBuilder.PRIMARY_KEY_NAME).addColumns(columns).setPrimaryKey().addToTable(d.getTable(actual));}
  private static void unique(Database d,String name,String table,String... columns)throws Exception{String actual=accessTable(table);new IndexBuilder(name).addColumns(columns).setUnique().addToTable(d.getTable(actual));}
  private static void relationship(Database d,String name,String primaryTable,String primaryField,String foreignTable,String foreignField)throws Exception{String p=accessTable(primaryTable),f=accessTable(foreignTable);new RelationshipBuilder(p,f).addColumns(primaryField,foreignField).setName(name).setReferentialIntegrity().toRelationship(d);}
  private static void dataset(Table ds,Table f,Table k,String code,String table,String family,String grain,String key,String[][] fields)throws Exception{String actual=table; if(table.startsWith("kids_")){String prefix=switch(family){case "ENTITY"->"__ent_";case "RELATION"->"__rel_";case "RAW"->"__raw_";case "STATISTICAL"->"__stat_";default->"__";}; actual=prefix+table;} ds.addRow(code,actual,family,grain);for(String[] x:fields)f.addRow(code,x[0],x[1],x[2],String.valueOf(requiredField(x[0])));k.addRow(code,key,"KIDS_STATISTICAL_INPUT".equals(code)?"PRIMARY":"NATURAL","1");}
  private static boolean requiredField(String field){return !Set.of("label_ka","label_en","valid_to","parent_item_ref","title_ka","title_en","path_ka","path_en","period_normalized","value_decimal","denominator_text","supersedes_source_row_key").contains(field);}
  private static void rel(Table r,String code,String fd,String ff,String td,String tf,String card)throws Exception{r.addRow(code,fd,ff,td,tf,card,"true");}
  private static ColumnBuilder[] cols(Object... a){ColumnBuilder[] out=new ColumnBuilder[a.length/2];for(int i=0;i<a.length;i+=2)out[i/2]=new ColumnBuilder((String)a[i],(DataType)a[i+1]);return out;}
  private static Table table(Database d,String name,ColumnBuilder[] cols)throws Exception{TableBuilder b=new TableBuilder(name);for(ColumnBuilder c:cols)b.addColumn(c);return b.toTable(d);} private static Table text(Database d,String name,String... fields)throws Exception{TableBuilder b=new TableBuilder(name);for(String f:fields)b.addColumn(new ColumnBuilder(f,DataType.TEXT));return b.toTable(d);}private static Table memo(Database d,String name,String... fields)throws Exception{TableBuilder b=new TableBuilder(name);for(String f:fields)b.addColumn(new ColumnBuilder(f,DataType.MEMO));return b.toTable(d);}
}
