package org.base.api.service.platform;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import jakarta.annotation.PreDestroy;

import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.MessageDigest;
import java.time.LocalDateTime;
import java.util.*;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.RejectedExecutionException;

/** Durable asynchronous export/query operation boundary. */
@Service
public class PlatformAsyncOperationService {
    private final JdbcTemplate control; private final CanonicalPageDataService pages; private final ObjectMapper json; private final Path exportDir; private final long maxExportBytes; private final int maxRequestBytes; private final ThreadPoolExecutor executor=new ThreadPoolExecutor(2,2,0L,TimeUnit.MILLISECONDS,new ArrayBlockingQueue<>(32),new ThreadPoolExecutor.AbortPolicy());
    public PlatformAsyncOperationService(@Qualifier("primaryJdbcTemplate") JdbcTemplate control,CanonicalPageDataService pages,ObjectMapper json,@Value("${storage.export-dir:api/storage/access_exports}") String exportDir,@Value("${platform.query.max-export-bytes:52428800}") long maxExportBytes,@Value("${platform.query.max-request-bytes:262144}") int maxRequestBytes){if(maxExportBytes<1||maxRequestBytes<1)throw new IllegalArgumentException("query limits must be positive");this.control=control;this.pages=pages;this.json=json;this.exportDir=Paths.get(exportDir);this.maxExportBytes=maxExportBytes;this.maxRequestBytes=maxRequestBytes;}
    public Map<String,Object> submit(String contract,int pageId,Map<String,Object> request){return submit(contract,pageId,null,request);}
    public Map<String,Object> submit(String contract,int pageId,String idempotencyKey,Map<String,Object> request){try{String body=json.writeValueAsString(request);if(body.getBytes(StandardCharsets.UTF_8).length>maxRequestBytes)throw new IllegalArgumentException("Operation request exceeds size limit");String key=normalizeKey(idempotencyKey);String fingerprint=hex(MessageDigest.getInstance("SHA-256").digest((contract+"\n"+pageId+"\n"+body).getBytes(StandardCharsets.UTF_8)));if(key!=null){List<Map<String,Object>> existing=control.queryForList("SELECT TOP 1 operation_id,request_hash FROM platform.api_operation WHERE idempotency_key=?",key);if(!existing.isEmpty()){if(!fingerprint.equalsIgnoreCase(String.valueOf(existing.get(0).get("request_hash"))))throw new IllegalArgumentException("Idempotency-Key was already used with a different request");return status(((Number)existing.get(0).get("operation_id")).longValue());}}try{control.update("INSERT INTO platform.api_operation(operation_type,status,contract_code,page_id,request_json,idempotency_key,request_hash) VALUES('EXPORT','QUEUED',?,?,?,?,?)",contract,pageId,body,key,fingerprint);}catch(org.springframework.dao.DataIntegrityViolationException duplicate){Map<String,Object> existing=control.queryForMap("SELECT TOP 1 operation_id,request_hash FROM platform.api_operation WHERE idempotency_key=?",key);if(!fingerprint.equalsIgnoreCase(String.valueOf(existing.get("request_hash"))))throw new IllegalArgumentException("Idempotency-Key was already used with a different request");return status(((Number)existing.get("operation_id")).longValue());}Long id=control.queryForObject("SELECT CAST(SCOPE_IDENTITY() AS BIGINT)",Long.class);try{executor.execute(()->run(id,contract,pageId,request));}catch(RejectedExecutionException rejected){control.update("UPDATE platform.api_operation SET status='FAILED',error_code='OPERATION_QUEUE_FULL',error_detail='Operation queue is full',completed_at=SYSUTCDATETIME() WHERE operation_id=?",id);throw new IllegalStateException("Asynchronous operation queue is full");}return status(id);}catch(Exception e){throw e instanceof IllegalStateException ? (IllegalStateException)e : new IllegalStateException("Unable to create asynchronous operation",e);}}
    public Map<String,Object> submit(String contract,int pageId,String idempotencyKey,Map<String,Object> request,String requestedBy){String owner=owner(requestedBy);try{String body=json.writeValueAsString(request);if(body.getBytes(StandardCharsets.UTF_8).length>maxRequestBytes)throw new IllegalArgumentException("Operation request exceeds size limit");String key=normalizeKey(idempotencyKey);String fingerprint=hex(MessageDigest.getInstance("SHA-256").digest((contract+"\n"+pageId+"\n"+body).getBytes(StandardCharsets.UTF_8)));if(key!=null){List<Map<String,Object>> existing=control.queryForList("SELECT TOP 1 operation_id,request_hash FROM platform.api_operation WHERE requested_by=? AND idempotency_key=?",owner,key);if(!existing.isEmpty()){if(!fingerprint.equalsIgnoreCase(String.valueOf(existing.get(0).get("request_hash"))))throw new IllegalArgumentException("Idempotency-Key was already used with a different request");return status(((Number)existing.get(0).get("operation_id")).longValue(),owner,false);}}try{control.update("INSERT INTO platform.api_operation(operation_type,status,contract_code,page_id,request_json,idempotency_key,request_hash,requested_by) VALUES('EXPORT','QUEUED',?,?,?,?,?,?)",contract,pageId,body,key,fingerprint,owner);}catch(org.springframework.dao.DataIntegrityViolationException duplicate){Map<String,Object> existing=control.queryForMap("SELECT TOP 1 operation_id,request_hash FROM platform.api_operation WHERE requested_by=? AND idempotency_key=?",owner,key);if(!fingerprint.equalsIgnoreCase(String.valueOf(existing.get("request_hash"))))throw new IllegalArgumentException("Idempotency-Key was already used with a different request");return status(((Number)existing.get("operation_id")).longValue(),owner,false);}Long id=control.queryForObject("SELECT CAST(SCOPE_IDENTITY() AS BIGINT)",Long.class);try{executor.execute(()->run(id,contract,pageId,request));}catch(RejectedExecutionException rejected){control.update("UPDATE platform.api_operation SET status='FAILED',error_code='OPERATION_QUEUE_FULL',error_detail='Operation queue is full',completed_at=SYSUTCDATETIME() WHERE operation_id=?",id);throw new IllegalStateException("Asynchronous operation queue is full");}return status(id,owner,false);}catch(Exception e){throw e instanceof IllegalStateException ? (IllegalStateException)e : new IllegalStateException("Unable to create asynchronous operation",e);}}
    private static String normalizeKey(String key){if(key==null||key.isBlank())return null;String value=key.trim();if(value.length()>128||!value.matches("[A-Za-z0-9._~-]+"))throw new IllegalArgumentException("Invalid Idempotency-Key");return value;}
    private static String owner(String value){if(value==null||value.isBlank()||value.length()>256)throw new IllegalArgumentException("Operation owner is invalid");return value;}
    @PreDestroy
    void shutdown(){executor.shutdown();}
    public Map<String,Object> status(long id){return control.queryForMap("SELECT operation_id,operation_type,status,contract_code,page_id,progress,result_uri,result_checksum,error_code,created_at,started_at,completed_at FROM platform.api_operation WHERE operation_id=?",id);}
    public Map<String,Object> status(long id,String requestedBy,boolean admin){return control.queryForMap("SELECT operation_id,operation_type,status,contract_code,page_id,progress,result_uri,result_checksum,error_code,created_at,started_at,completed_at FROM platform.api_operation WHERE operation_id=? AND (?=1 OR requested_by=?)",id,admin?1:0,owner(requestedBy));}
    public void cancel(long id){int n=control.update("UPDATE platform.api_operation SET status='CANCELLED',completed_at=SYSUTCDATETIME() WHERE operation_id=? AND status IN('QUEUED','RUNNING')",id);if(n==0)throw new IllegalArgumentException("Operation is not cancellable: "+id);}
    public void cancel(long id,String requestedBy,boolean admin){int n=control.update("UPDATE platform.api_operation SET status='CANCELLED',completed_at=SYSUTCDATETIME() WHERE operation_id=? AND (?=1 OR requested_by=?) AND status IN('QUEUED','RUNNING')",id,admin?1:0,owner(requestedBy));if(n==0)throw new IllegalArgumentException("Operation is not cancellable");}
    private void run(long id,String contract,int pageId,Map<String,Object> request){Path file=null;try{control.update("UPDATE platform.api_operation SET status='RUNNING',started_at=SYSUTCDATETIME(),progress=10 WHERE operation_id=?",id);Map<String,Object> filters=objectMap(request.get("filters"));Map<String,Object> where=objectMap(request.get("where"));int page=intValue(request.get("page"),1),limit=Math.min(intValue(request.get("limit"),1000),1000);Map<String,Object> result=pages.read(contract,pageId,page,limit,text(request.get("metricCode")),text(request.get("carrierCode")),text(request.get("periodFrom")),text(request.get("periodTo")),text(request.get("ageGroup")),filters,where);ExportFormatRegistry.Format selected=ExportFormatRegistry.require(text(request.get("format")));byte[] bytes;String extension=selected.extension();if("NDJSON".equals(selected.code())){StringBuilder out=new StringBuilder();Object rows=result.get("data");if(rows instanceof Iterable<?> it)for(Object row:it)out.append(json.writeValueAsString(row)).append('\n');else out.append(json.writeValueAsString(result)).append('\n');bytes=out.toString().getBytes(StandardCharsets.UTF_8);}else if("CSV".equals(selected.code())){bytes=toCsv(result).getBytes(StandardCharsets.UTF_8);}else{bytes=json.writerWithDefaultPrettyPrinter().writeValueAsBytes(result);}if(bytes.length>maxExportBytes)throw new IllegalArgumentException("Export exceeds configured size limit");Files.createDirectories(exportDir);file=exportDir.resolve("operation-"+id+"."+extension);Files.write(file,bytes,StandardOpenOption.CREATE,StandardOpenOption.TRUNCATE_EXISTING);String checksum=hex(MessageDigest.getInstance("SHA-256").digest(bytes));control.update("UPDATE platform.api_operation SET status='SUCCEEDED',progress=100,result_uri=?,result_checksum=?,completed_at=SYSUTCDATETIME() WHERE operation_id=?",file.toAbsolutePath().toString(),checksum,id);}catch(Exception e){if(file!=null)try{Files.deleteIfExists(file);}catch(Exception ignored){}control.update("UPDATE platform.api_operation SET status='FAILED',error_code='OPERATION_FAILED',error_detail=?,completed_at=SYSUTCDATETIME() WHERE operation_id=? AND status<>'CANCELLED'",truncate(e.getMessage()),id);}}
    private String toCsv(Map<String,Object> result)throws Exception{Object rows=result.get("data");if(!(rows instanceof List<?> list)||list.isEmpty())return "";Set<String> columns=new LinkedHashSet<>();for(Object row:list)if(row instanceof Map<?,?> m)for(Object key:m.keySet())columns.add(String.valueOf(key));StringBuilder out=new StringBuilder();out.append(String.join(",",columns)).append('\n');for(Object row:list){if(!(row instanceof Map<?,?> m))continue;boolean first=true;for(String c:columns){if(!first)out.append(',');first=false;Object raw=m.get(c);String v=raw==null?"":String.valueOf(raw);out.append('"').append(v.replace("\"","\"\"")).append('"');}out.append('\n');}return out.toString();}
    private static Map<String,Object> objectMap(Object o){return o instanceof Map<?,?> m?(Map<String,Object>)(Map<?,?>)m:Map.of();}
    private static int intValue(Object o,int d){try{return o==null?d:Integer.parseInt(String.valueOf(o));}catch(Exception e){return d;}}
    private static String text(Object o){return o==null?null:String.valueOf(o);}
    private static String truncate(String s){return s==null?"operation failed":s.substring(0,Math.min(1900,s.length()));}
    private static String hex(byte[] b){StringBuilder s=new StringBuilder();for(byte x:b)s.append(String.format("%02x",x));return s.toString();}
}
